CREATE TABLE IF NOT EXISTS roles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE,
 permissions_json JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id BIGINT UNSIGNED NULL,
 username VARCHAR(80) NOT NULL UNIQUE, display_name VARCHAR(120) NULL, email VARCHAR(190) NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 is_admin BOOLEAN NOT NULL DEFAULT FALSE, force_password_change BOOLEAN NOT NULL DEFAULT TRUE,
 active BOOLEAN NOT NULL DEFAULT TRUE, partner_sales_access BOOLEAN NOT NULL DEFAULT FALSE, last_login_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tags (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, color CHAR(7) NOT NULL DEFAULT '#546e7a', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_permissions (
 role_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 access_level ENUM('hidden','read','write') NOT NULL DEFAULT 'write', PRIMARY KEY(role_id,tag_id),
 FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contacts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL,
 company VARCHAR(190) NULL, job_title VARCHAR(150) NULL, email VARCHAR(190) NULL, phone VARCHAR(60) NULL,
 address TEXT NULL, website VARCHAR(255) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(last_name), INDEX(company), INDEX(email),
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS companies (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL UNIQUE,
 website VARCHAR(255) NULL, phone VARCHAR(60) NULL, address TEXT NULL, notes TEXT NULL,
 owner_id BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_tags (
 contact_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(contact_id,tag_id),
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opportunities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, owner_id BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NULL, title VARCHAR(190) NOT NULL,
 score ENUM('high','medium','low','keep_in_touch','not_buyer') NOT NULL DEFAULT 'medium', value DECIMAL(12,2) NULL,
 status ENUM('open','won','lost') NOT NULL DEFAULT 'open', source_type ENUM('none','event','other') NOT NULL DEFAULT 'none',
 source_event_id BIGINT UNSIGNED NULL, source_note TEXT NULL, expected_close_date DATE NULL, probability TINYINT UNSIGNED NULL, active BOOLEAN NOT NULL DEFAULT TRUE, closed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opportunity_contacts (
 opportunity_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(opportunity_id,contact_id), FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS partner_performance_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, partner_user_id BIGINT UNSIGNED NOT NULL, reviewer_user_id BIGINT UNSIGNED NULL,
 decision VARCHAR(30) NOT NULL, rating TINYINT UNSIGNED NULL, notes TEXT NULL, review_date DATE NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(partner_user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(partner_user_id,review_date)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 body TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_saved_views (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL,
 filters_json JSON NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE, position INT NOT NULL DEFAULT 100,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_relationships (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, related_contact_id BIGINT UNSIGNED NOT NULL,
 relationship_type VARCHAR(80) NOT NULL DEFAULT 'Related contact', notes VARCHAR(255) NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY(contact_id,related_contact_id),
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(related_contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_field_changes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 field_name VARCHAR(100) NOT NULL, old_value TEXT NULL, new_value TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(contact_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, event_type ENUM('webinar','conference','presentation','other') NOT NULL,
 starts_at DATETIME NOT NULL, presentation_title VARCHAR(190) NULL, abstract TEXT NULL,
 booking_url VARCHAR(500) NULL, conference_url VARCHAR(500) NULL, venue_address TEXT NULL,
 slides_path VARCHAR(255) NULL, slides_original_name VARCHAR(255) NULL, presenter_contact_id BIGINT UNSIGNED NULL, presenter_name VARCHAR(190) NULL,
 created_by BIGINT UNSIGNED NULL, owner_id BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(presenter_contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_attendees (
 event_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, attended BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY(event_id,contact_id), FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_presenters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL,
 presenter_type ENUM('user','contact') NOT NULL, presenter_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id,presenter_type,presenter_id),
 FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS saved_reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL,
 chart_type ENUM('bar','pie','doughnut') NOT NULL DEFAULT 'bar', group_by VARCHAR(40) NOT NULL,
 filters_json JSON NOT NULL, shared BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL,
 entity_type VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, details_json JSON NULL,
 ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(entity_type,entity_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS application_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, level VARCHAR(20) NOT NULL,
 message VARCHAR(500) NOT NULL, context_json JSON NULL, user_id BIGINT UNSIGNED NULL,
 ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(level,created_at), INDEX(created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_settings (
 setting_key VARCHAR(80) PRIMARY KEY, setting_value TEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reminders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,due_at,completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_reminders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,due_at,completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS system_alerts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, created_by BIGINT UNSIGNED NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(active,due_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS system_alert_states (
 system_alert_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 snoozed_until DATETIME NULL, completed_at DATETIME NULL, PRIMARY KEY(system_alert_id,user_id),
 FOREIGN KEY(system_alert_id) REFERENCES system_alerts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS api_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, token_prefix VARCHAR(16) NOT NULL,
 access_mode VARCHAR(30) NOT NULL DEFAULT 'upsert', active BOOLEAN NOT NULL DEFAULT TRUE, last_used_at DATETIME NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS api_contact_sources (
 api_user_id BIGINT UNSIGNED NOT NULL, external_id VARCHAR(190) NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(api_user_id,external_id), FOREIGN KEY(api_user_id) REFERENCES api_users(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS option_lists (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, list_key VARCHAR(80) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL, description VARCHAR(255) NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS option_values (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, list_id BIGINT UNSIGNED NOT NULL,
 code VARCHAR(80) NOT NULL, label VARCHAR(120) NOT NULL, color CHAR(7) NULL,
 position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(list_id,code), FOREIGN KEY(list_id) REFERENCES option_lists(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_default_tags (
 user_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,tag_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_tag_subscriptions (
 user_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,tag_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_notification_preferences (
 user_id BIGINT UNSIGNED PRIMARY KEY, alert_notifications BOOLEAN NOT NULL DEFAULT FALSE,
 alert_frequency ENUM('on_alert','daily_summary') NOT NULL DEFAULT 'on_alert', daily_summary_time TIME NOT NULL DEFAULT '08:00:00',
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_notification_deliveries (
 user_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,contact_id,tag_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_groups (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL UNIQUE,
 position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_fields (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_group_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL,
 field_type VARCHAR(30) NOT NULL DEFAULT 'text', position INT NOT NULL DEFAULT 0, required BOOLEAN NOT NULL DEFAULT FALSE,
 validation_pattern VARCHAR(255) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_conditions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_id BIGINT UNSIGNED NOT NULL,
 depends_on_field_id BIGINT UNSIGNED NOT NULL, operator ENUM('equals','not_equals','is_empty','not_empty') NOT NULL DEFAULT 'equals', expected_value TEXT NULL,
 FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE,
 FOÁnÌ¢Gß≤⁄Óù∆≠y“(80) NOT NULL UNIQUE, destination_url VARCHAR(2000) NOT NULL,
 campaign_name VARCHAR(190) NULL, channel VARCHAR(120) NULL, variant VARCHAR(120) NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(active,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS promotional_link_clicks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, promotional_link_id BIGINT UNSIGNED NOT NULL,
 clicked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, visitor_hash CHAR(64) NOT NULL,
 referrer VARCHAR(2000) NULL, user_agent VARCHAR(1000) NULL, device_type VARCHAR(30) NOT NULL DEFAULT 'Other',
 utm_source VARCHAR(190) NULL, utm_medium VARCHAR(190) NULL, utm_campaign VARCHAR(190) NULL,
 query_json JSON NULL,
 FOREIGN KEY(promotional_link_id) REFERENCES promotional_links(id) ON DELETE CASCADE,
 INDEX(promotional_link_id,clicked_at), INDEX(promotional_link_id,visitor_hash)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS knowledge_base_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL,
 item_type ENUM('text','file') NOT NULL DEFAULT 'text', body LONGTEXT NULL,
 stored_name VARCHAR(255) NULL, original_name VARCHAR(255) NULL, mime_type VARCHAR(120) NULL,
 extracted_text LONGTEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(item_type,updated_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS lead_magnets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(190) NOT NULL, magnet_type VARCHAR(80) NOT NULL, other_type VARCHAR(190) NULL,
 target_audience TEXT NOT NULL, desired_outcome TEXT NULL, audience_problem TEXT NULL,
 tone VARCHAR(120) NULL, call_to_action TEXT NULL, brand_requirements TEXT NULL, additional_instructions TEXT NULL,
 content_html LONGTEXT NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft',
 public_slug VARCHAR(80) NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, published_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(status,updated_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS lead_magnet_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, lead_magnet_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NULL, role ENUM('user','assistant') NOT NULL, message LONGTEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(lead_magnet_id) REFERENCES lead_magnets(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(lead_magnet_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS crm_forms (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(80) NOT NULL UNIQUE,
 visibility ENUM('public','private') NOT NULL DEFAULT 'public', thank_you_message TEXT NOT NULL,
 submit_label VARCHAR(120) NOT NULL DEFAULT 'Submit',
 download_lead_magnet_id BIGINT UNSIGNED NULL, fixed_tag_ids JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(download_lead_magnet_id) REFERENCES lead_magnets(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS crm_form_fields (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, form_id BIGINT UNSIGNED NOT NULL, field_key VARCHAR(80) NOT NULL,
 field_type VARCHAR(30) NOT NULL, label VARCHAR(190) NOT NULL, placeholder VARCHAR(255) NULL,
 options_json JSON NULL, crm_field VARCHAR(80) NULL, required BOOLEAN NOT NULL DEFAULT FALSE,
 validation_pattern VARCHAR(255) NULL, calculation VARCHAR(500) NULL, position INT NOT NULL DEFAULT 0,
 UNIQUE(form_id,field_key), FOREIGN KEY(form_id) REFERENCES crm_forms(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS crm_form_rules (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, form_id BIGINT UNSIGNED NOT NULL, target_field_id BIGINT UNSIGNED NULL,
 source_field_id BIGINT UNSIGNED NOT NULL, operator VARCHAR(30) NOT NULL, comparison_value VARCHAR(500) NULL,
 action ENUM('show','hide','tag') NOT NULL DEFAULT 'show', tag_id BIGINT UNSIGNED NULL,
 FOREIGN KEY(form_id) REFERENCES crm_forms(id) ON DELETE CASCADE,
 FOREIGN KEY(target_field_id) REFERENCES crm_form_fields(id) ON DELETE CASCADE,
 FOREIGN KEY(source_field_id) REFERENCES crm_form_fields(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS crm_form_submissions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, form_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NULL,
 values_json JSON NOT NULL, ip_hash CHAR(64) NOT NULL, submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(form_id) REFERENCES crm_forms(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE SET NULL, INDEX(form_id,submitted_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sites (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE,
 status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', primary_domain VARCHAR(255) NULL,
 tracking_enabled BOOLEAN NOT NULL DEFAULT TRUE, consent_mode ENUM('notice','required','disabled') NOT NULL DEFAULT 'notice',
 retention_days SMALLINT UNSIGNED NOT NULL DEFAULT 365, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_domains (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, site_id BIGINT UNSIGNED NOT NULL, hostname VARCHAR(255) NOT NULL UNIQUE,
 verification_token CHAR(64) NOT NULL, status ENUM('pending','verified','active','failed') NOT NULL DEFAULT 'pending',
 tls_status ENUM('pending','active','failed') NOT NULL DEFAULT 'pending', is_primary BOOLEAN NOT NULL DEFAULT FALSE,
 last_checked_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE, INDEX(site_id,status)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_pages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, site_id BIGINT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL,
 slug VARCHAR(160) NOT NULL, title VARCHAR(255) NULL, meta_description VARCHAR(500) NULL,
 project_json LONGTEXT NULL, html LONGTEXT NULL, css LONGTEXT NULL, custom_js LONGTEXT NULL,
 is_home BOOLEAN NOT NULL DEFAULT FALSE, status ENUM('draft','published') NOT NULL DEFAULT 'draft',
 published_at DATETIME NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE(site_id,slug), FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_page_versions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, page_id BIGINT UNSIGNED NOT NULL, version_number INT UNSIGNED NOT NULL,
 project_json LONGTEXT NULL, html LONGTEXT NULL, css LONGTEXT NULL, custom_js LONGTEXT NULL,
 created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(page_id,version_number), FOREIGN KEY(page_id) REFERENCES site_pages(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_visitors (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, visitor_key CHAR(36) NOT NULL UNIQUE, contact_id BIGINT UNSIGNED NULL,
 first_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE SET NULL, INDEX(contact_id,last_seen_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_sessions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, visitor_id BIGINT UNSIGNED NOT NULL, site_id BIGINT UNSIGNED NOT NULL,
 session_key CHAR(36) NOT NULL UNIQUE, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, last_activity_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 ended_at DATETIME NULL, entry_page_id BIGINT UNSIGNED NULL, exit_page_id BIGINT UNSIGNED NULL,
 referrer VARCHAR(2000) NULL, utm_source VARCHAR(190) NULL, utm_medium VARCHAR(190) NULL, utm_campaign VARCHAR(190) NULL,
 device_type VARCHAR(30) NULL, ip_hash CHAR(64) NULL,
 FOREIGN KEY(visitor_id) REFERENCES site_visitors(id) ON DELETE CASCADE, FOREIGN KEY(site_id) REFERENCES sites(id) ON DELETE CASCADE,
 FOREIGN KEY(entry_page_id) REFERENCES site_pages(id) ON DELETE SET NULL, FOREIGN KEY(exit_page_id) REFERENCES site_pages(id) ON DELETE SET NULL,
 INDEX(site_id,started_at), INDEX(visitor_id,last_activity_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_page_views (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, session_id BIGINT UNSIGNED NOT NULL, page_id BIGINT UNSIGNED NOT NULL,
 viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, engaged_seconds INT UNSIGNED NOT NULL DEFAULT 0,
 FOREIGN KEY(session_id) REFERENCES site_sessions(id) ON DELETE CASCADE, FOREIGN KEY(page_id) REFERENCES site_pages(id) ON DELETE CASCADE,
 INDEX(page_id,viewed_at), INDEX(session_id,viewed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS site_conversions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, session_id BIGINT UNSIGNED NULL, page_id BIGINT UNSIGNED NULL,
 contact_id BIGINT UNSIGNED NULL, conversion_type VARCHAR(60) NOT NULL, entity_type VARCHAR(60) NULL, entity_id BIGINT UNSIGNED NULL,
 metadata_json JSON NULL, converted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(session_id) REFERENCES site_sessions(id) ON DELETE SET NULL, FOREIGN KEY(page_id) REFERENCES site_pages(id) ON DELETE SET NULL,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE SET NULL, INDEX(conversion_type,converted_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_calendars (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, owner_user_id BIGINT UNSIGNED NULL,
 external_provider_id BIGINT UNSIGNED NULL,
 calendar_type ENUM('individual','round_robin','collective') NOT NULL DEFAULT 'individual', timezone VARCHAR(80) NOT NULL DEFAULT 'America/New_York',
 active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_calendar_members (
 calendar_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, weight SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 PRIMARY KEY(calendar_id,user_id), FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_availability_rules (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, calendar_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 weekday TINYINT UNSIGNED NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL,
 FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(calendar_id,weekday)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_meeting_types (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, calendar_id BIGINT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL,
 external_service_id BIGINT UNSIGNED NULL,
 slug VARCHAR(100) NOT NULL UNIQUE, description TEXT NULL, duration_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 30,
 buffer_before SMALLINT UNSIGNED NOT NULL DEFAULT 0, buffer_after SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 minimum_notice_hours SMALLINT UNSIGNED NOT NULL DEFAULT 4, location_type ENUM('video','phone','in_person','custom') NOT NULL DEFAULT 'video',
 location_details VARCHAR(500) NULL, tag_ids JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bookings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, meeting_type_id BIGINT UNSIGNED NOT NULL, calendar_id BIGINT UNSIGNED NOT NULL,
 assigned_user_id BIGINT UNSIGNED NULL, contact_id BIGINT UNSIGNED NULL, session_id BIGINT UNSIGNED NULL,
 attendee_name VARCHAR(190) NOT NULL, attendee_email VARCHAR(190) NOT NULL, attendee_phone VARCHAR(80) NULL,
 starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, timezone VARCHAR(80) NOT NULL, answers_json JSON NULL,
 status ENUM('confirmed','cancelled','completed','no_show') NOT NULL DEFAULT 'confirmed', cancel_token CHAR(64) NOT NULL UNIQUE,
 external_appointment_id BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(meeting_type_id) REFERENCES booking_meeting_types(id), FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id),
 FOREIGN KEY(assigned_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
 FOREIGN KEY(session_id) REFERENCES site_sessions(id) ON DELETE SET NULL, INDEX(assigned_user_id,starts_at), INDEX(calendar_id,starts_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS calendar_connections (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, provider ENUM('google','microsoft','caldav') NOT NULL,
 account_email VARCHAR(190) NULL, access_token_enc LONGTEXT NULL, refresh_token_enc LONGTEXT NULL, expires_at DATETIME NULL,
 external_calendar_id VARCHAR(500) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, last_sync_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id,provider,account_email), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
