CREATE TABLE IF NOT EXISTS roles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE,
 permissions_json JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id BIGINT UNSIGNED NULL,
 username VARCHAR(80) NOT NULL UNIQUE, display_name VARCHAR(120) NULL, email VARCHAR(190) NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 is_admin BOOLEAN NOT NULL DEFAULT FALSE, force_password_change BOOLEAN NOT NULL DEFAULT TRUE,
 active BOOLEAN NOT NULL DEFAULT TRUE, partner_sales_access BOOLEAN NOT NULL DEFAULT FALSE, last_login_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tags (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, color CHAR(7) NOT NULL DEFAULT '#546e7a', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_permissions (
 role_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 access_level ENUM('hidden','read','write') NOT NULL DEFAULT 'write', PRIMARY KEY(role_id,tag_id),
 FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contacts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL,
 company VARCHAR(190) NULL, job_title VARCHAR(150) NULL, email VARCHAR(190) NULL, phone VARCHAR(60) NULL,
 address TEXT NULL, website VARCHAR(255) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(last_name), INDEX(company), INDEX(email),
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS companies (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL UNIQUE,
 website VARCHAR(255) NULL, phone VARCHAR(60) NULL, address TEXT NULL, notes TEXT NULL,
 owner_id BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_tags (
 contact_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(contact_id,tag_id),
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opportunities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, owner_id BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NULL, title VARCHAR(190) NOT NULL,
 score ENUM('high','medium','low','keep_in_touch','not_buyer') NOT NULL DEFAULT 'medium', value DECIMAL(12,2) NULL,
 status ENUM('open','won','lost') NOT NULL DEFAULT 'open', source_type ENUM('none','event','other') NOT NULL DEFAULT 'none',
 source_event_id BIGINT UNSIGNED NULL, source_note TEXT NULL, expected_close_date DATE NULL, probability TINYINT UNSIGNED NULL, active BOOLEAN NOT NULL DEFAULT TRUE, closed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opportunity_contacts (
 opportunity_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(opportunity_id,contact_id), FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS partner_performance_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, partner_user_id BIGINT UNSIGNED NOT NULL, reviewer_user_id BIGINT UNSIGNED NULL,
 decision VARCHAR(30) NOT NULL, rating TINYINT UNSIGNED NULL, notes TEXT NULL, review_date DATE NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(partner_user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(partner_user_id,review_date)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 body TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_saved_views (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL,
 filters_json JSON NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE, position INT NOT NULL DEFAULT 100,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_relationships (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, related_contact_id BIGINT UNSIGNED NOT NULL,
 relationship_type VARCHAR(80) NOT NULL DEFAULT 'Related contact', notes VARCHAR(255) NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY(contact_id,related_contact_id),
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(related_contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_field_changes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 field_name VARCHAR(100) NOT NULL, old_value TEXT NULL, new_value TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(contact_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, event_type ENUM('webinar','conference','presentation','other') NOT NULL,
 starts_at DATETIME NOT NULL, presentation_title VARCHAR(190) NULL, abstract TEXT NULL,
 booking_url VARCHAR(500) NULL, conference_url VARCHAR(500) NULL, venue_address TEXT NULL,
 slides_path VARCHAR(255) NULL, slides_original_name VARCHAR(255) NULL, presenter_contact_id BIGINT UNSIGNED NULL, presenter_name VARCHAR(190) NULL,
 created_by BIGINT UNSIGNED NULL, owner_id BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(presenter_contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_attendees (
 event_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, attended BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY(event_id,contact_id), FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_presenters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL,
 presenter_type ENUM('user','contact') NOT NULL, presenter_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id,presenter_type,presenter_id),
 FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS saved_reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL,
 chart_type ENUM('bar','pie','doughnut') NOT NULL DEFAULT 'bar', group_by VARCHAR(40) NOT NULL,
 filters_json JSON NOT NULL, shared BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL,
 entity_type VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, details_json JSON NULL,
 ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(entity_type,entity_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS application_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, level VARCHAR(20) NOT NULL,
 message VARCHAR(500) NOT NULL, context_json JSON NULL, user_id BIGINT UNSIGNED NULL,
 ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(level,created_at), INDEX(created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_settings (
 setting_key VARCHAR(80) PRIMARY KEY, setting_value TEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reminders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,due_at,completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_reminders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,due_at,completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS system_alerts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, created_by BIGINT UNSIGNED NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(active,due_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS system_alert_states (
 system_alert_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 snoozed_until DATETIME NULL, completed_at DATETIME NULL, PRIMARY KEY(system_alert_id,user_id),
 FOREIGN KEY(system_alert_id) REFERENCES system_alerts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS api_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, token_prefix VARCHAR(16) NOT NULL,
 access_mode VARCHAR(30) NOT NULL DEFAULT 'upsert', active BOOLEAN NOT NULL DEFAULT TRUE, last_used_at DATETIME NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS api_contact_sources (
 api_user_id BIGINT UNSIGNED NOT NULL, external_id VARCHAR(190) NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(api_user_id,external_id), FOREIGN KEY(api_user_id) REFERENCES api_users(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS option_lists (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, list_key VARCHAR(80) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL, description VARCHAR(255) NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS option_values (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, list_id BIGINT UNSIGNED NOT NULL,
 code VARCHAR(80) NOT NULL, label VARCHAR(120) NOT NULL, color CHAR(7) NULL,
 position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(list_id,code), FOREIGN KEY(list_id) REFERENCES option_lists(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_default_tags (
 user_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,tag_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_tag_subscriptions (
 user_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,tag_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_notification_preferences (
 user_id BIGINT UNSIGNED PRIMARY KEY, alert_notifications BOOLEAN NOT NULL DEFAULT FALSE,
 alert_frequency ENUM('on_alert','daily_summary') NOT NULL DEFAULT 'on_alert', daily_summary_time TIME NOT NULL DEFAULT '08:00:00',
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_notification_deliveries (
 user_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,contact_id,tag_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_groups (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL UNIQUE,
 position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_fields (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_group_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL,
 field_type VARCHAR(30) NOT NULL DEFAULT 'text', position INT NOT NULL DEFAULT 0, required BOOLEAN NOT NULL DEFAULT FALSE,
 validation_pattern VARCHAR(255) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_conditions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_id BIGINT UNSIGNED NOT NULL,
 depends_on_field_id BIGINT UNSIGNED NOT NULL, operator ENUM('equals','not_equals','is_empty','not_empty') NOT NULL DEFAULT 'equals', expected_value TEXT NULL,
 FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE,
 FOREIGN KEY(depends_on_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_options (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_id BIGINT UNSIGNED NOT NULL,
 option_value VARCHAR(190) NOT NULL, position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(custom_field_id,option_value), FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_tags (
 custom_field_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(custom_field_id,tag_id), FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_custom_values (
 contact_id BIGINT UNSIGNED NOT NULL, custom_field_id BIGINT UNSIGNED NOT NULL, field_value TEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(contact_id,custom_field_id), FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_groups (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE,
 position INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
