CREATE TABLE IF NOT EXISTS roles (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE,
 permissions_json JSON NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, role_id BIGINT UNSIGNED NULL,
 username VARCHAR(80) NOT NULL UNIQUE, display_name VARCHAR(120) NULL, email VARCHAR(190) NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 is_admin BOOLEAN NOT NULL DEFAULT FALSE, force_password_change BOOLEAN NOT NULL DEFAULT TRUE,
 active BOOLEAN NOT NULL DEFAULT TRUE, partner_sales_access BOOLEAN NOT NULL DEFAULT FALSE, last_login_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS password_reset_tokens (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE,
 requested_ip VARCHAR(45) NULL, expires_at DATETIME NOT NULL, used_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,created_at), INDEX(expires_at,used_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tags (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, color CHAR(7) NOT NULL DEFAULT '#546e7a', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_permissions (
 role_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 access_level ENUM('hidden','read','write') NOT NULL DEFAULT 'write', PRIMARY KEY(role_id,tag_id),
 FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contacts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL,
 company VARCHAR(190) NULL, job_title VARCHAR(150) NULL, email VARCHAR(190) NULL, phone VARCHAR(60) NULL,
 address TEXT NULL, website VARCHAR(255) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(last_name), INDEX(company), INDEX(email),
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS companies (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL UNIQUE,
 website VARCHAR(255) NULL, phone VARCHAR(60) NULL, address TEXT NULL, notes TEXT NULL,
 owner_id BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_tags (
 contact_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(contact_id,tag_id),
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opportunities (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, owner_id BIGINT UNSIGNED NULL, created_by BIGINT UNSIGNED NULL, title VARCHAR(190) NOT NULL,
 score ENUM('high','medium','low','keep_in_touch','not_buyer') NOT NULL DEFAULT 'medium', value DECIMAL(12,2) NULL,
 status ENUM('open','won','lost') NOT NULL DEFAULT 'open', source_type ENUM('none','event','other') NOT NULL DEFAULT 'none',
 source_event_id BIGINT UNSIGNED NULL, source_note TEXT NULL, expected_close_date DATE NULL, probability TINYINT UNSIGNED NULL, active BOOLEAN NOT NULL DEFAULT TRUE, closed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS opportunity_contacts (
 opportunity_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(opportunity_id,contact_id), FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS partner_performance_reviews (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, partner_user_id BIGINT UNSIGNED NOT NULL, reviewer_user_id BIGINT UNSIGNED NULL,
 decision VARCHAR(30) NOT NULL, rating TINYINT UNSIGNED NULL, notes TEXT NULL, review_date DATE NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(partner_user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(partner_user_id,review_date)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS notes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 body TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_saved_views (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(100) NOT NULL,
 filters_json JSON NOT NULL, is_default BOOLEAN NOT NULL DEFAULT FALSE, position INT NOT NULL DEFAULT 100,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY(user_id,name), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_relationships (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, related_contact_id BIGINT UNSIGNED NOT NULL,
 relationship_type VARCHAR(80) NOT NULL DEFAULT 'Related contact', notes VARCHAR(255) NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY(contact_id,related_contact_id),
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(related_contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_field_changes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 field_name VARCHAR(100) NOT NULL, old_value TEXT NULL, new_value TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(contact_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL, event_type ENUM('webinar','conference','presentation','other') NOT NULL,
 starts_at DATETIME NOT NULL, presentation_title VARCHAR(190) NULL, abstract TEXT NULL,
 booking_url VARCHAR(500) NULL, conference_url VARCHAR(500) NULL, venue_address TEXT NULL,
 slides_path VARCHAR(255) NULL, slides_original_name VARCHAR(255) NULL, presenter_contact_id BIGINT UNSIGNED NULL, presenter_name VARCHAR(190) NULL,
 created_by BIGINT UNSIGNED NULL, owner_id BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(presenter_contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_attendees (
 event_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, attended BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY(event_id,contact_id), FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_presenters (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL,
 presenter_type ENUM('user','contact') NOT NULL, presenter_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id,presenter_type,presenter_id),
 FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS saved_reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL,
 chart_type ENUM('bar','pie','doughnut') NOT NULL DEFAULT 'bar', group_by VARCHAR(40) NOT NULL,
 filters_json JSON NOT NULL, shared BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS scheduled_reports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL,
 report_type ENUM('weekly_pipeline','monthly_new_contacts') NOT NULL,
 recipient_emails TEXT NOT NULL, weekday TINYINT UNSIGNED NULL, send_time TIME NOT NULL DEFAULT '08:00:00',
 timezone VARCHAR(80) NOT NULL DEFAULT 'America/New_York', next_run_at DATETIME NOT NULL,
 last_run_at DATETIME NULL, last_status ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
 last_error VARCHAR(1000) NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(active,next_run_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL,
 entity_type VARCHAR(80) NOT NULL, entity_id BIGINT UNSIGNED NULL, details_json JSON NULL,
 ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(entity_type,entity_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS application_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, level VARCHAR(20) NOT NULL,
 message VARCHAR(500) NOT NULL, context_json JSON NULL, user_id BIGINT UNSIGNED NULL,
 ip_address VARCHAR(45) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(level,created_at), INDEX(created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS operational_alert_states (
 alert_key VARCHAR(120) PRIMARY KEY, current_status ENUM('healthy','warning','error') NOT NULL DEFAULT 'healthy',
 consecutive_failures INT UNSIGNED NOT NULL DEFAULT 0, last_message VARCHAR(1000) NULL,
 last_notified_at DATETIME NULL, last_checked_at DATETIME NOT NULL,
 recovered_at DATETIME NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS app_settings (
 setting_key VARCHAR(80) PRIMARY KEY, setting_value TEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reminders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,due_at,completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS event_reminders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, completed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(user_id,due_at,completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS system_alerts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, created_by BIGINT UNSIGNED NULL,
 message TEXT NOT NULL, due_at DATETIME NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(active,due_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS system_alert_states (
 system_alert_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 snoozed_until DATETIME NULL, completed_at DATETIME NULL, PRIMARY KEY(system_alert_id,user_id),
 FOREIGN KEY(system_alert_id) REFERENCES system_alerts(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS api_users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, token_prefix VARCHAR(16) NOT NULL,
 access_mode VARCHAR(30) NOT NULL DEFAULT 'upsert', active BOOLEAN NOT NULL DEFAULT TRUE, last_used_at DATETIME NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS api_contact_sources (
 api_user_id BIGINT UNSIGNED NOT NULL, external_id VARCHAR(190) NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(api_user_id,external_id), FOREIGN KEY(api_user_id) REFERENCES api_users(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS option_lists (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, list_key VARCHAR(80) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL, description VARCHAR(255) NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS option_values (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, list_id BIGINT UNSIGNED NOT NULL,
 code VARCHAR(80) NOT NULL, label VARCHAR(120) NOT NULL, color CHAR(7) NULL,
 position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(list_id,code), FOREIGN KEY(list_id) REFERENCES option_lists(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_default_tags (
 user_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,tag_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_tag_subscriptions (
 user_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,tag_id), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_notification_preferences (
 user_id BIGINT UNSIGNED PRIMARY KEY, alert_notifications BOOLEAN NOT NULL DEFAULT FALSE,
 alert_frequency ENUM('on_alert','daily_summary') NOT NULL DEFAULT 'on_alert', daily_summary_time TIME NOT NULL DEFAULT '08:00:00',
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_notification_deliveries (
 user_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 delivered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,contact_id,tag_id),
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_groups (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL UNIQUE,
 position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_fields (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_group_id BIGINT UNSIGNED NULL, name VARCHAR(150) NOT NULL,
 field_type VARCHAR(30) NOT NULL DEFAULT 'text', position INT NOT NULL DEFAULT 0, required BOOLEAN NOT NULL DEFAULT FALSE,
 validation_pattern VARCHAR(255) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_conditions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_id BIGINT UNSIGNED NOT NULL,
 depends_on_field_id BIGINT UNSIGNED NOT NULL, operator ENUM('equals','not_equals','is_empty','not_empty') NOT NULL DEFAULT 'equals', expected_value TEXT NULL,
 FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE,
 FOREIGN KEY(depends_on_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_options (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, custom_field_id BIGINT UNSIGNED NOT NULL,
 option_value VARCHAR(190) NOT NULL, position INT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE,
 UNIQUE(custom_field_id,option_value), FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS custom_field_tags (
 custom_field_id BIGINT UNSIGNED NOT NULL, tag_id BIGINT UNSIGNED NOT NULL,
 PRIMARY KEY(custom_field_id,tag_id), FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE,
 FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS contact_custom_values (
 contact_id BIGINT UNSIGNED NOT NULL, custom_field_id BIGINT UNSIGNED NOT NULL, field_value TEXT NULL,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(contact_id,custom_field_id), FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(custom_field_id) REFERENCES custom_fields(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tag_groups (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE,
 position INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS promotional_links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL,
 slug VARCHAR(80) NOT NULL UNIQUE, destination_url VARCHAR(2000) NOT NULL,
 campaign_name VARCHAR(190) NULL, channel VARCHAR(120) NULL, variant VARCHAR(120) NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(active,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS promotional_link_clicks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, promotional_link_id BIGINT UNSIGNED NOT NULL,
 clicked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, visitor_hash CHAR(64) NOT NULL,
 referrer VARCHAR(2000) NULL, user_agent VARCHAR(1000) NULL, device_type VARCHAR(30) NOT NULL DEFAULT 'Other',
 utm_source VARCHAR(190) NULL, utm_medium VARCHAR(190) NULL, utm_campaign VARCHAR(190) NULL,
 query_json JSON NULL,
 FOREIGN KEY(promotional_link_id) REFERENCES promotional_links(id) ON DELETE CASCADE,
 INDEX(promotional_link_id,clicked_at), INDEX(promotional_link_id,visitor_hash)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS knowledge_base_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(190) NOT NULL,
 item_type ENUM('text','file') NOT NULL DEFAULT 'text', body LONGTEXT NULL,
 stored_name VARCHAR(255) NULL, original_name VARCHAR(255) NULL, mime_type VARCHAR(120) NULL,
 extracted_text LONGTEXT NULL, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
…3469 tokens truncated…me VARCHAR(190) NULL,
 from_address VARCHAR(320) NOT NULL, reply_to VARCHAR(320) NULL, smtp_host VARCHAR(255) NOT NULL,
 smtp_port SMALLINT UNSIGNED NOT NULL DEFAULT 587, smtp_encryption ENUM('none','tls','ssl') NOT NULL DEFAULT 'tls',
 smtp_username VARCHAR(320) NULL, smtp_password_enc TEXT NULL, hourly_limit INT UNSIGNED NOT NULL DEFAULT 100,
 daily_limit INT UNSIGNED NOT NULL DEFAULT 500, weight SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 active BOOLEAN NOT NULL DEFAULT TRUE, health_status ENUM('healthy','warning','disabled') NOT NULL DEFAULT 'healthy',
 last_error VARCHAR(1000) NULL, last_used_at DATETIME NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE(from_address), FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(active,health_status,last_used_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS email_mailbox_sends (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, mailbox_id BIGINT UNSIGNED NOT NULL, recipient VARCHAR(320) NOT NULL,
 message_type ENUM('transactional','marketing') NOT NULL, status ENUM('sent','failed') NOT NULL,
 error_message VARCHAR(1000) NULL, sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(mailbox_id) REFERENCES email_mailboxes(id) ON DELETE CASCADE, INDEX(mailbox_id,sent_at), INDEX(status,sent_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS email_queue (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, mailbox_id BIGINT UNSIGNED NULL, recipient VARCHAR(320) NOT NULL,
 subject VARCHAR(500) NOT NULL, body_text MEDIUMTEXT NOT NULL, transactional BOOLEAN NOT NULL DEFAULT FALSE,
 status ENUM('queued','processing','sent','failed','cancelled') NOT NULL DEFAULT 'queued', attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
 available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, last_error VARCHAR(1000) NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, sent_at DATETIME NULL,
 FOREIGN KEY(mailbox_id) REFERENCES email_mailboxes(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(status,available_at), INDEX(mailbox_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS email_templates (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, subject VARCHAR(500) NOT NULL, body_text MEDIUMTEXT NOT NULL,
 owner_user_id BIGINT UNSIGNED NULL, shared BOOLEAN NOT NULL DEFAULT FALSE, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(owner_user_id,shared,active)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_email_signatures (
 user_id BIGINT UNSIGNED PRIMARY KEY, signature_text TEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS workflows (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL,
 trigger_type ENUM('contact_created','tag_added','form_submitted','booking_created','opportunity_stage_changed','manual') NOT NULL,
 trigger_config JSON NULL, steps_json JSON NOT NULL, active BOOLEAN NOT NULL DEFAULT FALSE,
 created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(active,trigger_type)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS workflow_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, event_key VARCHAR(190) NULL UNIQUE, event_type VARCHAR(80) NOT NULL, contact_id BIGINT UNSIGNED NULL,
 entity_type VARCHAR(80) NULL, entity_id BIGINT UNSIGNED NULL, payload_json JSON NULL, processed_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
 INDEX(processed_at,created_at), INDEX(event_type,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS workflow_enrollments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, workflow_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 source_event_id BIGINT UNSIGNED NULL, status ENUM('active','completed','stopped','failed') NOT NULL DEFAULT 'active',
 current_step INT UNSIGNED NOT NULL DEFAULT 0, next_run_at DATETIME NULL, error_message VARCHAR(1000) NULL,
 started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, completed_at DATETIME NULL,
 FOREIGN KEY(workflow_id) REFERENCES workflows(id) ON DELETE CASCADE, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(source_event_id) REFERENCES workflow_events(id) ON DELETE SET NULL, INDEX(status,next_run_at), INDEX(workflow_id,contact_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS workflow_logs (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, enrollment_id BIGINT UNSIGNED NOT NULL, step_index INT UNSIGNED NULL,
 action_type VARCHAR(80) NOT NULL, status ENUM('success','failed','info') NOT NULL DEFAULT 'success', detail TEXT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(enrollment_id) REFERENCES workflow_enrollments(id) ON DELETE CASCADE,
 INDEX(enrollment_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_portals (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, slug VARCHAR(120) NOT NULL UNIQUE,
 headline VARCHAR(255) NOT NULL, description TEXT NULL, thank_you_message TEXT NULL, fixed_tag_ids JSON NULL,
 active BOOLEAN NOT NULL DEFAULT FALSE, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_categories (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, description TEXT NULL, position INT NOT NULL DEFAULT 0,
 active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(name)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resources (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, category_id BIGINT UNSIGNED NULL, title VARCHAR(255) NOT NULL, description TEXT NULL,
 resource_type ENUM('file','url','lead_magnet') NOT NULL, stored_name VARCHAR(255) NULL, original_name VARCHAR(255) NULL,
 mime_type VARCHAR(120) NULL, external_url VARCHAR(2000) NULL, lead_magnet_id BIGINT UNSIGNED NULL, tag_ids JSON NULL,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(category_id) REFERENCES resource_categories(id) ON DELETE SET NULL, FOREIGN KEY(lead_magnet_id) REFERENCES lead_magnets(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(category_id,active)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_portal_items (
 portal_id BIGINT UNSIGNED NOT NULL, resource_id BIGINT UNSIGNED NOT NULL, position INT NOT NULL DEFAULT 0,
 PRIMARY KEY(portal_id,resource_id), FOREIGN KEY(portal_id) REFERENCES resource_portals(id) ON DELETE CASCADE,
 FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_access_sessions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, portal_id BIGINT UNSIGNED NOT NULL, contact_id BIGINT UNSIGNED NOT NULL,
 access_token CHAR(64) NOT NULL UNIQUE, visitor_id BIGINT UNSIGNED NULL, expires_at DATETIME NOT NULL, last_seen_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(portal_id) REFERENCES resource_portals(id) ON DELETE CASCADE,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE, FOREIGN KEY(visitor_id) REFERENCES site_visitors(id) ON DELETE SET NULL,
 INDEX(portal_id,contact_id), INDEX(expires_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS resource_engagements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, portal_id BIGINT UNSIGNED NOT NULL, resource_id BIGINT UNSIGNED NOT NULL,
 contact_id BIGINT UNSIGNED NOT NULL, access_session_id BIGINT UNSIGNED NULL, engagement_type ENUM('view','download','open') NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(portal_id) REFERENCES resource_portals(id) ON DELETE CASCADE,
 FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE CASCADE,
 FOREIGN KEY(access_session_id) REFERENCES resource_access_sessions(id) ON DELETE SET NULL, INDEX(resource_id,created_at), INDEX(contact_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS products (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, sku VARCHAR(100) NULL UNIQUE, description TEXT NULL,
 unit_price DECIMAL(12,2) NOT NULL DEFAULT 0, currency CHAR(3) NOT NULL DEFAULT 'USD', taxable BOOLEAN NOT NULL DEFAULT FALSE,
 active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quotes (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quote_number VARCHAR(60) NOT NULL UNIQUE, contact_id BIGINT UNSIGNED NOT NULL,
 opportunity_id BIGINT UNSIGNED NULL, owner_user_id BIGINT UNSIGNED NULL, title VARCHAR(255) NOT NULL,
 introduction TEXT NULL, terms TEXT NULL, currency CHAR(3) NOT NULL DEFAULT 'USD', subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
 discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0, tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0, total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
 status ENUM('draft','sent','viewed','accepted','declined','expired','paid','void') NOT NULL DEFAULT 'draft', valid_until DATE NULL,
 public_token CHAR(64) NOT NULL UNIQUE, sent_at DATETIME NULL, viewed_at DATETIME NULL, accepted_at DATETIME NULL, paid_at DATETIME NULL,
 created_by BIGINT UNSIGNED NULL, updated_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE RESTRICT, FOREIGN KEY(opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL,
 FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL, INDEX(status,valid_until), INDEX(contact_id,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quote_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quote_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NULL,
 description VARCHAR(1000) NOT NULL, quantity DECIMAL(12,2) NOT NULL DEFAULT 1, unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
 discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0, tax_percent DECIMAL(5,2) NOT NULL DEFAULT 0, line_total DECIMAL(12,2) NOT NULL DEFAULT 0,
 position INT NOT NULL DEFAULT 0, FOREIGN KEY(quote_id) REFERENCES quotes(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE SET NULL, INDEX(quote_id,position)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quote_acceptances (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quote_id BIGINT UNSIGNED NOT NULL, signer_name VARCHAR(190) NOT NULL,
 signer_email VARCHAR(320) NOT NULL, accepted_terms BOOLEAN NOT NULL, signature_text VARCHAR(500) NULL, ip_hash CHAR(64) NULL,
 user_agent VARCHAR(500) NULL, accepted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(quote_id) REFERENCES quotes(id) ON DELETE CASCADE, INDEX(quote_id,accepted_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS quote_payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, quote_id BIGINT UNSIGNED NOT NULL, provider VARCHAR(40) NOT NULL DEFAULT 'stripe',
 checkout_session_id VARCHAR(255) NULL UNIQUE, payment_intent_id VARCHAR(255) NULL, amount DECIMAL(12,2) NOT NULL,
 currency CHAR(3) NOT NULL, status ENUM('pending','paid','failed','refunded','cancelled') NOT NULL DEFAULT 'pending',
 provider_url VARCHAR(2000) NULL, paid_at DATETIME NULL, payload_json JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(quote_id) REFERENCES quotes(id) ON DELETE CASCADE, INDEX(status,created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_calendars (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(190) NOT NULL, owner_user_id BIGINT UNSIGNED NULL,
 external_provider_id BIGINT UNSIGNED NULL,
 calendar_type ENUM('individual','round_robin','collective') NOT NULL DEFAULT 'individual', timezone VARCHAR(80) NOT NULL DEFAULT 'America/New_York',
 active BOOLEAN NOT NULL DEFAULT TRUE, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(owner_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_calendar_members (
 calendar_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, weight SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 PRIMARY KEY(calendar_id,user_id), FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_availability_exceptions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, calendar_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, reason VARCHAR(255) NULL, created_by BIGINT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 INDEX(calendar_id,user_id,starts_at,ends_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_availability_rules (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, calendar_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL,
 weekday TINYINT UNSIGNED NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL,
 FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 INDEX(calendar_id,weekday)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_meeting_types (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, calendar_id BIGINT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL,
 external_service_id BIGINT UNSIGNED NULL,
 slug VARCHAR(100) NOT NULL UNIQUE, description TEXT NULL, duration_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 30,
 buffer_before SMALLINT UNSIGNED NOT NULL DEFAULT 0, buffer_after SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 minimum_notice_hours SMALLINT UNSIGNED NOT NULL DEFAULT 4, location_type ENUM('video','phone','in_person','custom') NOT NULL DEFAULT 'video',
 location_details VARCHAR(500) NULL, tag_ids JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
 created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bookings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, meeting_type_id BIGINT UNSIGNED NOT NULL, calendar_id BIGINT UNSIGNED NOT NULL,
 assigned_user_id BIGINT UNSIGNED NULL, contact_id BIGINT UNSIGNED NULL, session_id BIGINT UNSIGNED NULL,
 attendee_name VARCHAR(190) NOT NULL, attendee_email VARCHAR(190) NOT NULL, attendee_phone VARCHAR(80) NULL,
 starts_at DATETIME NOT NULL, ends_at DATETIME NOT NULL, timezone VARCHAR(80) NOT NULL, answers_json JSON NULL,
 status ENUM('confirmed','cancelled','completed','no_show') NOT NULL DEFAULT 'confirmed', cancel_token CHAR(64) NOT NULL UNIQUE,
 external_appointment_id BIGINT UNSIGNED NULL, meeting_url VARCHAR(2000) NULL, calendar_sync_status ENUM('pending','synced','partial','failed') NOT NULL DEFAULT 'pending', calendar_sync_error VARCHAR(1000) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(meeting_type_id) REFERENCES booking_meeting_types(id), FOREIGN KEY(calendar_id) REFERENCES booking_calendars(id),
 FOREIGN KEY(assigned_user_id) REFERENCES users(id) ON DELETE SET NULL, FOREIGN KEY(contact_id) REFERENCES contacts(id) ON DELETE SET NULL,
 FOREIGN KEY(session_id) REFERENCES site_sessions(id) ON DELETE SET NULL, INDEX(assigned_user_id,starts_at), INDEX(calendar_id,starts_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_questions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, meeting_type_id BIGINT UNSIGNED NOT NULL, label VARCHAR(190) NOT NULL,
 field_key VARCHAR(80) NOT NULL, field_type ENUM('text','textarea','select','checkbox') NOT NULL DEFAULT 'text',
 options_json JSON NULL, required BOOLEAN NOT NULL DEFAULT FALSE, position INT NOT NULL DEFAULT 0,
 UNIQUE(meeting_type_id,field_key), FOREIGN KEY(meeting_type_id) REFERENCES booking_meeting_types(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_notification_log (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, booking_id BIGINT UNSIGNED NOT NULL, notification_type VARCHAR(40) NOT NULL,
 recipient VARCHAR(190) NOT NULL, scheduled_for DATETIME NULL, sent_at DATETIME NULL, status ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
 error_message VARCHAR(500) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE, INDEX(status,scheduled_for), UNIQUE(booking_id,notification_type,recipient)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS calendar_connections (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, provider ENUM('google','microsoft','caldav') NOT NULL,
 account_email VARCHAR(190) NULL, access_token_enc LONGTEXT NULL, refresh_token_enc LONGTEXT NULL, expires_at DATETIME NULL,
 external_calendar_id VARCHAR(500) NULL, active BOOLEAN NOT NULL DEFAULT TRUE, sync_status ENUM('pending','healthy','error') NOT NULL DEFAULT 'pending',
 last_error VARCHAR(500) NULL, last_sync_at DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id,provider,account_email), FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_calendar_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, booking_id BIGINT UNSIGNED NOT NULL, connection_id BIGINT UNSIGNED NOT NULL,
 external_event_id VARCHAR(1000) NOT NULL, external_url VARCHAR(2000) NULL, etag VARCHAR(500) NULL,
 sync_status ENUM('synced','failed','deleted') NOT NULL DEFAULT 'synced', last_error VARCHAR(1000) NULL,
 last_synced_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(booking_id,connection_id), FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
 FOREIGN KEY(connection_id) REFERENCES calendar_connections(id) ON DELETE CASCADE, INDEX(sync_status,last_synced_at)
) ENGINE=InnoDB;

