<?php
declare(strict_types=1);

function api_payload_tag_names(array $payload):array{$values=[];$append=function(mixed $value)use(&$values,&$append):void{if(is_array($value)){if(array_key_exists('name',$value))$append($value['name']);else foreach($value as $item)$append($item);return;}foreach(preg_split('/\s*,\s*/',(string)$value)?:[] as $name){$name=trim($name);if($name!==''&&!in_array($name,$values,true))$values[]=$name;}};if(array_key_exists('tags',$payload))$append($payload['tags']);if(array_key_exists('tag',$payload))$append($payload['tag']);$numbered=[];foreach($payload as $key=>$value)if(preg_match('/^tag(\d+)$/i',(string)$key,$match))$numbered[(int)$match[1]]=$value;ksort($numbered);foreach($numbered as $value)$append($value);return $values;}
function api_audit_rejection(array $data,int $status):void{if($status<400)return;static $written=false;if($written)return;$written=true;$payload=$GLOBALS['api_request_payload']??[];$apiUser=$GLOBALS['api_request_user']??null;$details=['api_user_id'=>$apiUser?(int)$apiUser['id']:null,'endpoint'=>$GLOBALS['path']??'','method'=>$GLOBALS['method']??'','http_status'=>$status,'outcome'=>'rejected','reason'=>(string)($data['error']??'Request rejected'),'email'=>strtolower(trim((string)($payload['email']??''))),'external_id'=>trim((string)($payload['external_id']??$payload['ghl_contact_id']??'')),'requested_tags'=>api_payload_tag_names(is_array($payload)?$payload:[])];try{db()->prepare('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details_json,ip_address) VALUES(NULL,?,?,?,?,?)')->execute(['api_request_rejected','api_request',null,json_encode($details,JSON_UNESCAPED_SLASHES),$_SERVER['REMOTE_ADDR']??null]);}catch(Throwable $e){error_log('API rejection audit failed: '.$e->getMessage());}}
function api_response(array $data,int $status=200): never { api_audit_rejection($data,$status);http_response_code($status);header('Content-Type: application/json');header('Cache-Control: no-store');echo json_encode($data,JSON_UNESCAPED_SLASHES);exit; }
function api_token(): string {
    $header=$_SERVER['HTTP_AUTHORIZATION']??$_SERVER['REDIRECT_HTTP_AUTHORIZATION']??'';
    if(preg_match('/^Bearer\s+(.+)$/i',$header,$m))return trim($m[1]);
    return trim((string)($_SERVER['HTTP_X_API_TOKEN']??''));
}
$rawBody=(string)file_get_contents('php://input');$decodedBody=json_decode($rawBody,true);$GLOBALS['api_request_payload']=is_array($decodedBody)?$decodedBody:[];
if($path!=='/api/v1/contacts')api_response(['error'=>'API endpoint not found.'],404);
$token=api_token();if($token==='')api_response(['error'=>'Missing authentication token.'],401);
$stmt=db()->prepare('SELECT * FROM api_users WHERE token_hash=? AND active=1');$stmt->execute([hash('sha256',$token)]);$apiUser=$stmt->fetch();
if(!$apiUser)api_response(['error'=>'Invalid or revoked authentication token.'],401);
$GLOBALS['api_request_user']=$apiUser;
db()->prepare('UPDATE api_users SET last_used_at=NOW() WHERE id=?')->execute([$apiUser['id']]);

if($method!=='POST')api_response(['error'=>'Method not allowed.'],405);
$contentType=strtolower($_SERVER['CONTENT_TYPE']??'');if(!str_contains($contentType,'application/json'))api_response(['error'=>'Content-Type must be application/json.'],415);
$payload=$decodedBody;if(!is_array($payload))api_response(['error'=>'Request body must be valid JSON.'],400);

$externalId=trim((string)($payload['external_id']??$payload['ghl_contact_id']??''));$email=strtolower(trim((string)($payload['email']??'')));
if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))api_response(['error'=>'Email is invalid.','field'=>'email'],422);
$pdo=db();$pdo->beginTransaction();
try{
    $contactId=0;
    if($externalId!==''){$s=$pdo->prepare('SELECT contact_id FROM api_contact_sources WHERE api_user_id=? AND external_id=?');$s->execute([$apiUser['id'],$externalId]);$contactId=(int)$s->fetchColumn();}
    if(!$contactId&&$email!==''){$s=$pdo->prepare('SELECT id FROM contacts WHERE LOWER(email)=? ORDER BY id LIMIT 1');$s->execute([$email]);$contactId=(int)$s->fetchColumn();}
    $created=!$contactId;$tagOnlyExisting=!$created&&$apiUser['access_mode']==='create_only';
    $fields=['first_name','last_name','company','job_title','email','phone','address','website','linkedin_url'];
    $linkedin=trim((string)($payload['linkedin_url']??''));if($linkedin!==''&&(!filter_var($linkedin,FILTER_VALIDATE_URL)||!in_array(strtolower((string)parse_url($linkedin,PHP_URL_SCHEME)),['http','https'],true)))throw new InvalidArgumentException('linkedin_url must be a valid HTTP or HTTPS URL.');
    if($created){$first=trim((string)($payload['first_name']??''));$last=trim((string)($payload['last_name']??''));if($first===''||$last==='')throw new InvalidArgumentException('first_name and last_name are required when creating a contact.');$pdo->prepare('INSERT INTO contacts(first_name,last_name,company,job_title,email,phone,address,website,linkedin_url) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$first,$last,trim((string)($payload['company']??''))?:null,trim((string)($payload['job_title']??''))?:null,$email?:null,trim((string)($payload['phone']??''))?:null,trim((string)($payload['address']??''))?:null,trim((string)($payload['website']??''))?:null,$linkedin?:null]);$contactId=(int)$pdo->lastInsertId();}
    elseif(!$tagOnlyExisting){$sets=[];$values=[];foreach($fields as $field)if(array_key_exists($field,$payload)){$value=trim((string)$payload[$field]);if($field==='email')$value=strtolower($value);$sets[]="$field=?";$values[]=$value?:null;}if($sets){$values[]=$contactId;$pdo->prepare('UPDATE contacts SET '.implode(',',$sets).' WHERE id=?')->execute($values);}}
    if($externalId!=='')$pdo->prepare('INSERT INTO api_contact_sources(api_user_id,external_id,contact_id) VALUES(?,?,?) ON DUPLICATE KEY UPDATE contact_id=VALUES(contact_id)')->execute([$apiUser['id'],$externalId,$contactId]);
    $tagIds=[];$tagNames=[];foreach(api_payload_tag_names($payload) as $name){if(mb_strlen($name)>100)continue;$s=$pdo->prepare('INSERT INTO tags(name,color) VALUES(?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)');$s->execute([$name,'#546e7a']);$tagIds[]=(int)$pdo->lastInsertId();$tagNames[]=$name;}
    if(!empty($payload['replace_tags'])&&$apiUser['access_mode']==='upsert')$pdo->prepare('DELETE FROM contact_tags WHERE contact_id=?')->execute([$contactId]);
    $s=$pdo->prepare('INSERT IGNORE INTO contact_tags(contact_id,tag_id) VALUES(?,?)');$tagsAdded=[];foreach(array_unique($tagIds) as $index=>$tagId){$s->execute([$contactId,$tagId]);if($s->rowCount())$tagsAdded[]=$tagNames[$index]??('Tag #'.$tagId);}
    if($created||$tagsAdded)schedule_tag_notifications($contactId);
    $company=trim((string)($payload['company']??''));if(!$tagOnlyExisting&&$company!==''){$s=$pdo->prepare('INSERT INTO companies(name) VALUES(?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)');$s->execute([$company]);$pdo->prepare('UPDATE contacts SET company_id=? WHERE id=?')->execute([(int)$pdo->lastInsertId(),$contactId]);}
    $customSaved=[];$normalize=fn(string $name)=>trim(strtolower((string)preg_replace('/[^a-z0-9]+/i','_',trim($name))),'_');
    $customPayload=$tagOnlyExisting?[]:(is_array($payload['custom_fields']??null)?$payload['custom_fields']:[]);if(!$tagOnlyExisting)foreach($payload as $key=>$value)if(str_starts_with((string)$key,'custom_'))$customPayload[substr((string)$key,7)]=$value;if($customPayload){$definitions=custom_field_definitions();$byName=[];foreach($definitions as $field)$byName[$normalize((string)$field['name'])]=$field;$save=$pdo->prepare('INSERT INTO contact_custom_values(contact_id,custom_field_id,field_value) VALUES(?,?,?) ON DUPLICATE KEY UPDATE field_value=VALUES(field_value)');foreach($customPayload as $name=>$value){$field=$byName[$normalize((string)$name)]??null;if(!$field)throw new InvalidArgumentException('Unknown custom field: '.$name);$value=trim((string)$value);if($field['field_type']==='list'&&!in_array($value,array_column($field['options'],'option_value'),true))throw new InvalidArgumentException('Invalid value for custom field '.$field['name'].'.');$save->execute([$contactId,(int)$field['id'],$value]);$customSaved[]=$field['name'];}}
    $notePayload=$tagOnlyExisting?[]:($payload['notes']??($payload['note']??[]));$notes=is_array($notePayload)?$notePayload:[$notePayload];$noteStmt=$pdo->prepare('INSERT INTO notes(contact_id,user_id,body) VALUES(?,NULL,?)');$notesAdded=0;foreach($notes as $note){$body=trim((string)$note);if($body==='')continue;$noteStmt->execute([$contactId,$body]);$notesAdded++;}
    $resultAction=$created?'created':($tagOnlyExisting?($tagsAdded?'tagged_existing':'matched_existing_no_change'):'updated');$auditAction=$created?'api_create':($tagOnlyExisting?($tagsAdded?'api_tag_existing':'api_no_change'):'api_update');
    $pdo->prepare('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,details_json,ip_address) VALUES(NULL,?,?,?,?,?)')->execute([$auditAction,'contact',$contactId,json_encode(['api_user_id'=>(int)$apiUser['id'],'outcome'=>$resultAction,'requested_tags'=>$tagNames,'tags_added'=>$tagsAdded,'custom_fields'=>$customSaved,'notes_added'=>$notesAdded,'external_id'=>$externalId]),$_SERVER['REMOTE_ADDR']??null]);smart_cache_bump(array_merge(['contacts','contact:'.$contactId,'reports:contacts','dashboard','opportunities'],$tagsAdded?['tags']:[]));
    $pdo->commit();api_response(['success'=>true,'action'=>$resultAction,'contact_id'=>$contactId,'external_id'=>$externalId?:null,'tags'=>$tagNames,'tags_added'=>$tagsAdded,'custom_fields'=>$customSaved,'notes_added'=>$notesAdded],$created?201:200);
}catch(InvalidArgumentException $e){if($pdo->inTransaction())$pdo->rollBack();api_response(['error'=>$e->getMessage()],422);}
catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();app_log('error','API contact processing failed',['exception'=>get_class($e),'message'=>$e->getMessage()]);error_log($e);api_response(['error'=>'Unable to process contact.'],500);}
