<?php
declare(strict_types=1);
if($path!=='/admin/custom-fields')return;if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}
if($method==='POST'){verify_csrf();$action=post('action');
    if($action==='create_group'){db()->prepare('INSERT INTO custom_field_groups(name,position) VALUES(?,?)')->execute([trim(post('name')),(int)post('position')]);audit('create','custom_field_group',(int)db()->lastInsertId());}
    elseif($action==='update_group'){$id=(int)post('group_id');db()->prepare('UPDATE custom_field_groups SET name=?,position=?,active=? WHERE id=?')->execute([trim(post('name')),(int)post('position'),post('active')?1:0,$id]);audit('update','custom_field_group',$id);}
    elseif($action==='create'){$types=['text','textarea','list','date','number','currency','checkbox','email','url'];$type=in_array(post('field_type'),$types,true)?post('field_type'):'text';$group=(int)post('group_id')?:null;db()->prepare('INSERT INTO custom_fields(custom_field_group_id,name,field_type,position) VALUES(?,?,?,?)')->execute([$group,trim(post('name')),$type,(int)post('position')]);audit('create','custom_field',(int)db()->lastInsertId());}
    elseif($action==='update'){$id=(int)post('field_id');$group=(int)post('group_id')?:null;db()->prepare('UPDATE custom_fields SET custom_field_group_id=?,name=?,position=?,required=?,validation_pattern=?,active=? WHERE id=?')->execute([$group,trim(post('name')),(int)post('position'),post('required')?1:0,trim(post('validation_pattern'))?:null,post('active')?1:0,$id]);db()->prepare('DELETE FROM custom_field_tags WHERE custom_field_id=?')->execute([$id]);$stmt=db()->prepare('INSERT INTO custom_field_tags(custom_field_id,tag_id) VALUES(?,?)');foreach(array_unique(array_map('intval',(array)post('condition_tags',[]))) as $tagId)if($tagId)$stmt->execute([$id,$tagId]);audit('update','custom_field',$id);}
    elseif($action==='add_condition'){$id=(int)post('field_id');$depends=(int)post('depends_on_field_id');$operator=in_array(post('operator'),['equals','not_equals','is_empty','not_empty'],true)?post('operator'):'equals';if($id===$depends)throw new RuntimeException('A field cannot depend on itself.');$expected=in_array($operator,['is_empty','not_empty'],true)?null:trim(post('expected_value'));db()->prepare('INSERT INTO custom_field_conditions(custom_field_id,depends_on_field_id,operator,expected_value) VALUES(?,?,?,?)')->execute([$id,$depends,$operator,$expected]);audit('create','custom_field_condition',(int)db()->lastInsertId());}
    elseif($action==='delete_condition'){db()->prepare('DELETE FROM custom_field_conditions WHERE id=?')->execute([(int)post('condition_id')]);audit('delete','custom_field_condition',(int)post('condition_id'));}
    elseif($action==='add_option'){$id=(int)post('field_id');db()->prepare('INSERT INTO custom_field_options(custom_field_id,option_value,position) VALUES(?,?,?)')->execute([$id,trim(post('option_value')),(int)post('position')]);audit('create','custom_field_option',(int)db()->lastInsertId(),['custom_field_id'=>$id]);}
    elseif($action==='toggle_option'){db()->prepare('UPDATE custom_field_options SET active=? WHERE id=?')->execute([post('active')?1:0,(int)post('option_id')]);audit('update','custom_field_option',(int)post('option_id'));}
    flash('success','Custom field configuration saved.');redirect('/admin/custom-fields');
}
$fields=custom_field_definitions(false);$tags=all_tags();$groups=db()->query('SELECT * FROM custom_field_groups ORDER BY position,name')->fetchAll();
layout('Custom fields',function()use($fields,$tags,$groups){?><div class="actions"><h1 style="margin:0">Custom fields</h1><span class="spacer"></span><a class="btn secondary" href="/admin/settings">Application settings</a></div>
<div class="card"><h2>Field groups</h2><p class="muted">Groups become section headings on contact forms and contact details.</p><?php foreach($groups as $group):?><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="update_group"><input type="hidden" name="group_id" value="<?=$group['id']?>"><input name="name" value="<?=e($group['name'])?>" required><input style="max-width:110px" type="number" name="position" value="<?=$group['position']?>" aria-label="Sort position"><label><input style="width:auto" type="checkbox" name="active" value="1" <?=$group['active']?'checked':''?>> Available</label><button>Save group</button></form><?php endforeach?><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="create_group"><input name="name" placeholder="New group name" required><input style="max-width:110px" type="number" name="position" value="100" aria-label="Sort position"><button>Add group</button></form></div>
<form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="create"><h2>Create custom field</h2><div class="form-grid"><label>Name<input name="name" required maxlength="150"></label><label>Section<select name="group_id"><option value="">Other information</option><?php foreach($groups as $group):?><option value="<?=$group['id']?>"><?=e($group['name'])?></option><?php endforeach?></select></label><label>Input type<select name="field_type"><option value="text">Freeform text</option><option value="list">Managed list</option></select></label><label>Sort position<input type="number" name="position" value="100"></label></div><button>Create field</button></form>
<?php foreach($fields as $field):?><div class="card"><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="update"><input type="hidden" name="field_id" value="<?=$field['id']?>"><div class="actions"><h2 style="margin:0"><?=e($field['name'])?></h2><span class="tag" style="background:#607d8b"><?=e($field['field_type'])?></span></div><div class="form-grid"><label>Name<input name="name" value="<?=e($field['name'])?>" required></label><label>Section<select name="group_id"><option value="">Other information</option><?php foreach($groups as $group):?><option value="<?=$group['id']?>" <?=((int)$field['custom_field_group_id']===(int)$group['id'])?'selected':''?>><?=e($group['name'])?></option><?php endforeach?></select></label><label>Sort position<input type="number" name="position" value="<?=$field['position']?>"></label><label><input style="width:auto" type="checkbox" name="active" value="1" <?=$field['active']?'checked':''?>> Available</label><label class="full">Show when contact has any of these tags <span class="muted">(leave empty to always show)</span><select name="condition_tags[]" multiple size="7"><?php foreach($tags as $tag):?><option value="<?=$tag['id']?>" <?=in_array((int)$tag['id'],$field['tag_ids'],true)?'selected':''?>><?=e(($tag['group_name']?$tag['group_name'].' — ':'').$tag['name'])?></option><?php endforeach?></select></label></div><button>Save field</button></form>
<hr><h3>Field value conditions</h3><p class="muted">All conditions below must match. Tag conditions must also match when configured.</p><?php foreach($field['conditions'] as $condition):?><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="delete_condition"><input type="hidden" name="condition_id" value="<?=$condition['id']?>"><span><strong><?=e($condition['depends_on_name'])?></strong> <?=e(str_replace('_',' ',$condition['operator']))?><?php if(!in_array($condition['operator'],['is_empty','not_empty'],true)):?> “<?=e($condition['expected_value'])?>”<?php endif?></span><button class="danger">Remove</button></form><?php endforeach?><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="add_condition"><input type="hidden" name="field_id" value="<?=$field['id']?>"><select name="depends_on_field_id" required><option value="">Choose controlling field…</option><?php foreach($fields as $candidate)if((int)$candidate['id']!==(int)$field['id']):?><option value="<?=$candidate['id']?>"><?=e($candidate['name'])?></option><?php endif?></select><select name="operator"><option value="equals">Equals</option><option value="not_equals">Does not equal</option><option value="is_empty">Is empty</option><option value="not_empty">Is not empty</option></select><input name="expected_value" placeholder="Value (when applicable)"><button>Add condition</button></form>
<?php if($field['field_type']==='list'):?><hr><h3>List values</h3><div class="checkboxes"><?php foreach($field['options'] as $option):?><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="toggle_option"><input type="hidden" name="option_id" value="<?=$option['id']?>"><label><input style="width:auto" type="checkbox" name="active" value="1" <?=$option['active']?'checked':''?> onchange="this.form.submit()"><?=e($option['option_value'])?></label></form><?php endforeach?></div><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="add_option"><input type="hidden" name="field_id" value="<?=$field['id']?>"><input name="option_value" placeholder="New list value" required><input style="max-width:100px" type="number" name="position" value="100" aria-label="Sort position"><button>Add value</button></form><?php endif?></div><?php endforeach?><?php });exit;
