<?php
declare(strict_types=1);

if(!function_exists('opportunity_contacts')){function opportunity_contacts(int $opportunityId): array {
    $s=db()->prepare('SELECT c.* FROM contacts c JOIN opportunity_contacts oc ON oc.contact_id=c.id WHERE oc.opportunity_id=? ORDER BY c.last_name,c.first_name');$s->execute([$opportunityId]);
    return array_values(array_filter($s->fetchAll(),fn($c)=>contact_access((int)$c['id'])!=='hidden'));
}}
if($path==='/opportunities'){
    require_permission('contacts.view');$score=trim((string)($_GET['score']??''));$status=trim((string)($_GET['status']??''));$source=trim((string)($_GET['source']??''));$recordView=trim((string)($_GET['view']??'mine'));$where=['o.active=1'];$params=[];
    if(in_array($score,option_codes('opportunity_score'),true)){$where[]='o.score=?';$params[]=$score;}if(in_array($status,option_codes('opportunity_status'),true)){$where[]='o.status=?';$params[]=$status;}if(in_array($source,option_codes('opportunity_source'),true)){$where[]='o.source_type=?';$params[]=$source;}
    if($recordView!=='all'){$where[]='COALESCE(o.owner_id,o.created_by)=?';$params[]=user()['id'];}
    $s=db()->prepare('SELECT o.*,e.title source_event FROM opportunities o LEFT JOIN events e ON e.id=o.source_event_id WHERE '.implode(' AND ',$where).' ORDER BY o.created_at DESC LIMIT 1000');$s->execute($params);$rows=array_values(array_filter($s->fetchAll(),fn($o)=>count(opportunity_contacts((int)$o['id']))>0));
    layout('Opportunities',function()use($rows,$score,$status,$source){?><div class="actions"><h1 style="margin:0">Opportunities</h1><span class="spacer"></span><?php if(can('contacts.edit')):?><a class="btn" href="/opportunities/new">Add opportunity</a><?php endif?></div><form class="card form-grid" method="get"><label>Score<select name="score"><option value="">Any</option><?php foreach(list_options('opportunity_score') as $option):?><option value="<?=e($option['code'])?>" <?=$score===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Status<select name="status"><option value="">Any</option><?php foreach(list_options('opportunity_status') as $option):?><option value="<?=e($option['code'])?>" <?=$status===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Source<select name="source"><option value="">Any</option><?php foreach(list_options('opportunity_source') as $option):?><option value="<?=e($option['code'])?>" <?=$source===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><div><button>Filter</button></div></form><div class="card"><table><thead><tr><th>Opportunity</th><th>Contacts</th><th>Score</th><th>Status</th><th>Source</th><th>Value</th></tr></thead><tbody><?php foreach($rows as $o):?><tr><td><a href="/opportunities/<?=$o['id']?>"><?=e($o['title'])?></a></td><td><?php foreach(opportunity_contacts((int)$o['id']) as $c):?><a href="/contacts/<?=$c['id']?>"><?=e($c['first_name'].' '.$c['last_name'])?></a><br><?php endforeach?></td><td><span class="tag" style="background:<?=e(option_color('opportunity_score',$o['score']))?>"><?=e(option_label('opportunity_score',$o['score']))?></span></td><td><?=e(option_label('opportunity_status',$o['status']))?></td><td><?=e($o['source_type']==='event'?$o['source_event']:(option_label('opportunity_source',$o['source_type']).($o['source_note']?' — '.$o['source_note']:'')))?></td><td><?=$o['value']!==null?'$'.number_format((float)$o['value'],2):''?></td></tr><?php endforeach?></tbody></table></div><?php });exit;
}
if($path==='/opportunities/new'){
    require_permission('contacts.edit');
    if($method==='POST'){verify_csrf();$contactIds=array_values(array_unique(array_filter(array_map('intval',(array)post('contacts',[])))));foreach($contactIds as $cid){if(contact_access($cid)==='hidden'){http_response_code(403);exit('Forbidden');}}if(!$contactIds){flash('error','Select at least one contact.');redirect('/opportunities/new');}$score=(string)post('score');$status=(string)post('status');if(!in_array($score,option_codes('opportunity_score'),true))$score=option_codes('opportunity_score')[0]??'medium';if(!in_array($status,option_codes('opportunity_status'),true))$status=option_codes('opportunity_status')[0]??'open';$source=post('source_type');if(!in_array($source,option_codes('opportunity_source'),true))$source='none';$eventId=$source==='event'?(int)post('source_event_id'):null;$note=!in_array($source,['none','event'],true)?trim((string)post('source_note')):null;db()->prepare('INSERT INTO opportunities(contact_id,owner_id,created_by,title,score,value,status,source_type,source_event_id,source_note,expected_close_date,probability) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$contactIds[0],user()['id'],user()['id'],trim((string)post('title')),$score,post('value')?:null,$status,$source,$eventId?:null,$note?:null,post('expected_close_date')?:null,min(100,max(0,(int)post('probability')))]);$id=(int)db()->lastInsertId();$s=db()->prepare('INSERT INTO opportunity_contacts(opportunity_id,contact_id) VALUES(?,?)');foreach($contactIds as $cid)$s->execute([$id,$cid]);audit('create','opportunity',$id,['contacts'=>$contactIds,'source'=>$source]);redirect('/opportunities/'.$id);}
    $contacts=array_values(array_filter(db()->query('SELECT id,first_name,last_name,company FROM contacts ORDER BY last_name,first_name')->fetchAll(),fn($c)=>contact_access((int)$c['id'])!=='hidden'));$events=db()->query('SELECT id,title,event_type,starts_at FROM events ORDER BY starts_at DESC')->fetchAll();
    layout('New opportunity',function()use($contacts,$events){?><h1>New opportunity</h1><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><div class="form-grid"><label>Opportunity name<input name="title" required></label><label>Value<input type="number" step="0.01" min="0" name="value"></label><label>Score<select name="score"><?php foreach(list_options('opportunity_score') as $option):?><option value="<?=e($option['code'])?>"><?=e($option['label'])?></option><?php endforeach?></select></label><label>Status<select name="status"><?php foreach(list_options('opportunity_status') as $option):?><option value="<?=e($option['code'])?>"><?=e($option['label'])?></option><?php endforeach?></select></label><label class="full">Linked contacts<select name="contacts[]" multiple size="8" required><?php foreach($contacts as $c):?><option value="<?=$c['id']?>"><?=e($c['last_name'].', '.$c['first_name'].' — '.$c['company'])?></option><?php endforeach?></select><span class="muted">Use Ctrl/Cmd to select multiple contacts.</span></label><label>Source<select name="source_type" id="opportunity-source"><?php foreach(list_options('opportunity_source') as $option):?><option value="<?=e($option['code'])?>"><?=e($option['label'])?></option><?php endforeach?></select></label><label id="source-event" hidden>Source event<select name="source_event_id"><option value="">Choose event</option><?php foreach($events as $e):?><option value="<?=$e['id']?>"><?=e($e['title'].' — '.$e['event_type'].' — '.$e['starts_at'])?></option><?php endforeach?></select></label><label id="source-other" class="full" hidden>Other source note<textarea name="source_note" rows="4" placeholder="Describe where this opportunity came from"></textarea></label></div><button>Create opportunity</button></form><script>const source=document.querySelector('#opportunity-source'),eventField=document.querySelector('#source-event'),otherField=document.querySelector('#source-other');function sourceFields(){eventField.hidden=source.value!=='event';otherField.hidden=['none','event'].includes(source.value)}source.addEventListener('change',sourceFields);sourceFields()</script><?php });exit;
}
if(preg_match('#^/opportunities/(\d+)$#',$path,$m)){
    require_permission('contacts.view');$id=(int)$m[1];$s=db()->prepare('SELECT o.*,e.title source_event,e.event_type source_event_type FROM opportunities o LEFT JOIN events e ON e.id=o.source_event_id WHERE o.id=?');$s->execute([$id]);$o=$s->fetch();if(!$o||!opportunity_contacts($id)){http_response_code(404);exit('Opportunity not found');}$contacts=opportunity_contacts($id);
    if($method==='POST'){require_permission('contacts.edit');verify_csrf();require_record_edit($o);$status=post('status');$score=post('score');if(!in_array($status,option_codes('opportunity_status'),true)||!in_array($score,option_codes('opportunity_score'),true)){flash('error','Invalid opportunity status.');}else{db()->prepare('UPDATE opportunities SET status=?,score=?,value=?,expected_close_date=?,probability=? WHERE id=?')->execute([$status,$score,post('value')?:null,post('expected_close_date')?:null,min(100,max(0,(int)post('probability'))),$id]);audit('update','opportunity',$id);flash('success','Opportunity updated.');}redirect('/opportunities/'.$id);}
    layout($o['title'],function()use($o,$contacts,$id){?><h1><?=e($o['title'])?></h1><div class="grid"><div class="card"><h2>Linked contacts</h2><?php foreach($contacts as $c):?><p><a href="/contacts/<?=$c['id']?>"><?=e($c['first_name'].' '.$c['last_name'])?></a><br><span class="muted"><?=e($c['company'])?></span></p><?php endforeach?></div><div class="card"><h2>Source</h2><?php if($o['source_type']==='event'):?><p>Event: <a href="/events/<?=$o['source_event_id']?>"><?=e($o['source_event'])?></a><br><span class="muted"><?=e($o['source_event_type'])?></span></p><?php elseif($o['source_type']==='other'):?><p><?=nl2br(e($o['source_note']))?></p><?php else:?><p class="muted">No source recorded.</p><?php endif?></div></div><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><h2>Opportunity details</h2><div class="form-grid"><label>Score<select name="score"><?php foreach(list_options('opportunity_score') as $option):?><option value="<?=e($option['code'])?>" <?=$o['score']===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Status<select name="status"><?php foreach(list_options('opportunity_status') as $option):?><option value="<?=e($option['code'])?>" <?=$o['status']===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Value<input type="number" step="0.01" min="0" name="value" value="<?=e($o['value'])?>"></label></div><?php if(can('contacts.edit')):?><button>Save opportunity</button><?php endif?></form><?php });exit;
}
