<?php
declare(strict_types=1);

if(!function_exists('opportunity_contacts')){function opportunity_contacts(int $opportunityId): array {
    $s=db()->prepare('SELECT c.* FROM contacts c JOIN opportunity_contacts oc ON oc.contact_id=c.id WHERE oc.opportunity_id=? ORDER BY c.last_name,c.first_name');$s->execute([$opportunityId]);
    return array_values(array_filter($s->fetchAll(),fn($c)=>contact_access((int)$c['id'])!=='hidden'));
}}
if($path==='/opportunities'){
    require_permission('contacts.view');$choiceValues=function(string $name,string $list):array{$raw=$_GET[$name]??[];$values=is_array($raw)?$raw:[$raw];return array_values(array_unique(array_filter(array_map(fn($value)=>trim((string)$value),$values),fn($value)=>in_array($value,option_codes($list),true))));};$choiceOperator=function(string $name):string{$operator=(string)($_GET[$name.'_operator']??'is');return in_array($operator,['is','is_not','any_of','none_of'],true)?$operator:'is';};$scoreValues=$choiceValues('score','opportunity_score');$statusValues=$choiceValues('status','opportunity_status');$sourceValues=$choiceValues('source','opportunity_source');$score=$scoreValues[0]??'';$status=$statusValues[0]??'';$source=$sourceValues[0]??'';$scoreOperator=$choiceOperator('score');$statusOperator=$choiceOperator('status');$sourceOperator=$choiceOperator('source');$recordView=trim((string)($_GET['view']??'mine'));$minimumValue=max(0,(float)($_GET['minimum_value']??0));$maximumValue=max(0,(float)($_GET['maximum_value']??0));$minimumProbability=max(0,min(100,(int)($_GET['minimum_probability']??0)));$closeFrom=trim((string)($_GET['close_from']??''));$closeTo=trim((string)($_GET['close_to']??''));$where=['o.active=1'];$params=[];
    $addChoiceFilter=function(string $column,array $values,string $operator)use(&$where,&$params):void{if(!$values)return;$negative=in_array($operator,['is_not','none_of'],true);if(in_array($operator,['is','is_not'],true))$values=array_slice($values,0,1);$marks=implode(',',array_fill(0,count($values),'?'));$where[]="$column ".($negative?'NOT IN':'IN')." ($marks)";array_push($params,...$values);};$addChoiceFilter('o.score',$scoreValues,$scoreOperator);$addChoiceFilter('o.status',$statusValues,$statusOperator);$addChoiceFilter('o.source_type',$sourceValues,$sourceOperator);if($minimumValue>0){$where[]='o.value>=?';$params[]=$minimumValue;}if($maximumValue>0){$where[]='o.value<=?';$params[]=$maximumValue;}if($minimumProbability>0){$where[]='o.probability>=?';$params[]=$minimumProbability;}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$closeFrom)){$where[]='o.expected_close_date>=?';$params[]=$closeFrom;}if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$closeTo)){$where[]='o.expected_close_date<=?';$params[]=$closeTo;}
    if($recordView!=='all'){$where[]='COALESCE(o.owner_id,o.created_by)=?';$params[]=user()['id'];}
    $sql='SELECT o.*,e.title source_event FROM opportunities o LEFT JOIN events e ON e.id=o.source_event_id WHERE '.implode(' AND ',$where).' ORDER BY o.created_at DESC LIMIT 1000';$cacheKey='opportunities:list:'.hash('sha256',json_encode([$sql,$params,(int)user()['id'],(int)user()['role_id']]));$rows=smart_cache_remember($cacheKey,['opportunities','contacts','tags','events','permissions'],function()use($sql,$params){$s=db()->prepare($sql);$s->execute($params);return array_values(array_filter($s->fetchAll(),fn($o)=>count(opportunity_contacts((int)$o['id']))>0));},300);
    layout('Opportunities',function()use($rows,$score,$status,$source){?><div class="actions"><h1 style="margin:0">Opportunities</h1><span class="spacer"></span><?php if(can('contacts.edit')):?><a class="btn" href="/opportunities/new">Add opportunity</a><?php endif?></div><form class="card form-grid" method="get"><label>Score<select name="score"><option value="">Any</option><?php foreach(list_options('opportunity_score') as $option):?><option value="<?=e($option['code'])?>" <?=$score===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Status<select name="status"><option value="">Any</option><?php foreach(list_options('opportunity_status') as $option):?><option value="<?=e($option['code'])?>" <?=$status===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Source<select name="source"><option value="">Any</option><?php foreach(list_options('opportunity_source') as $option):?><option value="<?=e($option['code'])?>" <?=$source===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><div><button>Filter</button></div></form><div class="card"><table><thead><tr><th>Opportunity</th><th>Contacts</th><th>Score</th><th>Status</th><th>Source</th><th>Value</th></tr></thead><tbody><?php foreach($rows as $o):?><tr><td><a href="/opportunities/<?=$o['id']?>"><?=e($o['title'])?></a></td><td><?php foreach(opportunity_contacts((int)$o['id']) as $c):?><a href="/contacts/<?=$c['id']?>"><?=e($c['first_name'].' '.$c['last_name'])?></a><br><?php endforeach?></td><td><span class="tag" style="background:<?=e(option_color('opportunity_score',$o['score']))?>"><?=e(option_label('opportunity_score',$o['score']))?></span></td><td><?=e(option_label('opportunity_status',$o['status']))?></td><td><?=e($o['source_type']==='event'?$o['source_event']:(option_label('opportunity_source',$o['source_type']).($o['source_note']?' — '.$o['source_note']:'')))?></td><td><?=$o['value']!==null?'$'.number_format((float)$o['value'],2):''?></td></tr><?php endforeach?></tbody></table></div><?php });exit;
}
if($path==='/opportunities/new'){
    require_permission('contacts.edit');
    if($method==='POST'){verify_csrf();$contactIds=array_values(array_unique(array_filter(array_map('intval',(array)post('contacts',[])))));foreach($contactIds as $cid){if(contact_access($cid)==='hidden'){http_response_code(403);exit('Forbidden');}}if(!$contactIds){flash('error','Select at least one contact.');redirect('/opportunities/new');}$score=(string)post('score');$status=(string)post('status');if(!in_array($score,option_codes('opportunity_score'),true))$score=option_codes('opportunity_score')[0]??'medium';if(!in_array($status,option_codes('opportunity_status'),true))$status=option_codes('opportunity_status')[0]??'open';$source=post('source_type');if(!in_array($source,option_codes('opportunity_source'),true))$source='none';$eventId=$source==='event'?(int)post('source_event_id'):null;$note=!in_array($source,['none','event'],true)?trim((string)post('source_note')):null;db()->prepare('INSERT INTO opportunities(contact_id,owner_id,created_by,title,score,value,status,source_type,source_event_id,source_note,expected_close_date,probability) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$contactIds[0],user()['id'],user()['id'],trim((string)post('title')),$score,post('value')?:null,$status,$source,$eventId?:null,$note?:null,post('expected_close_date')?:null,min(100,max(0,(int)post('probability')))]);$id=(int)db()->lastInsertId();$s=db()->prepare('INSERT INTO opportunity_contacts(opportunity_id,contact_id) VALUES(?,?)');foreach($contactIds as $cid)$s->execute([$id,$cid]);audit('create','opportunity',$id,['contacts'=>$contactIds,'source'=>$source]);redirect('/opportunities/'.$id);}
    $contacts=array_values(array_filter(db()->query('SELECT id,first_name,last_name,company FROM contacts ORDER BY last_name,first_name')->fetchAll(),fn($c)=>contact_access((int)$c['id'])!=='hidden'));$events=db()->query('SELECT id,title,event_type,starts_at FROM events ORDER BY starts_at DESC')->fetchAll();
    layout('New opportunity',function()use($contacts,$events){?><h1>New opportunity</h1><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><div class="form-grid"><label>Opportunity name<input name="title" required></label><label>Value<input type="number" step="0.01" min="0" name="value"></label><label>Score<select name="score"><?php foreach(list_options('opportunity_score') as $option):?><option value="<?=e($option['code'])?>"><?=e($option['label'])?></option><?php endforeach?></select></label><label>Status<select name="status"><?php foreach(list_options('opportunity_status') as $option):?><option value="<?=e($option['code'])?>"><?=e($option['label'])?></option><?php endforeach?></select></label><label class="full">Linked contacts<select name="contacts[]" multiple size="8" required><?php foreach($contacts as $c):?><option value="<?=$c['id']?>"><?=e($c['last_name'].', '.$c['first_name'].' — '.$c['company'])?></option><?php endforeach?></select><span class="muted">Use Ctrl/Cmd to select multiple contacts.</span></label><label>Source<select name="source_type" id="opportunity-source"><?php foreach(list_options('opportunity_source') as $option):?><option value="<?=e($option['code'])?>"><?=e($option['label'])?></option><?php endforeach?></select></label><label id="source-event" hidden>Source event<select name="source_event_id"><option value="">Choose event</option><?php foreach($events as $e):?><option value="<?=$e['id']?>"><?=e($e['title'].' — '.$e['event_type'].' — '.$e['starts_at'])?></option><?php endforeach?></select></label><label id="source-other" class="full" hidden>Other source note<textarea name="source_note" rows="4" placeholder="Describe where this opportunity came from"></textarea></label></div><button>Create opportunity</button></form><script>const source=document.querySelector('#opportunity-source'),eventField=document.querySelector('#source-event'),otherField=document.querySelector('#source-other');function sourceFields(){eventField.hidden=source.value!=='event';otherField.hidden=['none','event'].includes(source.value)}source.addEventListener('change',sourceFields);sourceFields()</script><?php });exit;
}
if(preg_match('#^/opportunities/(\d+)/notes$#',$path,$m)&&$method==='POST'){
    require_permission('opportunities.view');verify_csrf();$id=(int)$m[1];$s=db()->prepare('SELECT * FROM opportunities WHERE id=?');$s->execute([$id]);$opportunity=$s->fetch();
    if(!$opportunity||!opportunity_contacts($id)){http_response_code(404);exit('Opportunity not found');}
    $body=trim((string)post('body'));if($body===''){flash('error','Enter a note.');redirect('/opportunities/'.$id);}
    db()->prepare('INSERT INTO opportunity_notes(opportunity_id,user_id,body) VALUES(?,?,?)')->execute([$id,user()['id'],$body]);
    audit('create','opportunity_note',(int)db()->lastInsertId(),['opportunity_id'=>$id,'opportunity'=>$opportunity['title'],'note'=>$body]);
    flash('success','Opportunity note added.');redirect('/opportunities/'.$id);
}
if(preg_match('#^/opportunities/(\d+)/delete$#',$path,$m)&&$method==='POST'){
    require_permission('opportunities.edit');verify_csrf();$id=(int)$m[1];$s=db()->prepare('SELECT * FROM opportunities WHERE id=?');$s->execute([$id]);$opportunity=$s->fetch();
    if(!$opportunity){http_response_code(404);exit('Opportunity not found');}require_record_edit($opportunity);
    db()->beginTransaction();try{audit('delete','opportunity',$id,['opportunity'=>$opportunity['title'],'status'=>$opportunity['status'],'value'=>$opportunity['value']]);db()->prepare('DELETE FROM opportunities WHERE id=?')->execute([$id]);db()->commit();}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}
    flash('success','Opportunity deleted.');redirect('/opportunities');
}
if(preg_match('#^/opportunities/(\d+)$#',$path,$m)){
    require_permission('contacts.view');$id=(int)$m[1];$s=db()->prepare('SELECT o.*,e.title source_event,e.event_type source_event_type FROM opportunities o LEFT JOIN events e ON e.id=o.source_event_id WHERE o.id=?');$s->execute([$id]);$o=$s->fetch();if(!$o||!opportunity_contacts($id)){http_response_code(404);exit('Opportunity not found');}$contacts=opportunity_contacts($id);
    if($method==='POST'){require_permission('contacts.edit');verify_csrf();require_record_edit($o);$status=post('status');$score=post('score');if(!in_array($status,option_codes('opportunity_status'),true)||!in_array($score,option_codes('opportunity_score'),true)){flash('error','Invalid opportunity status.');}else{db()->prepare('UPDATE opportunities SET status=?,score=?,value=?,expected_close_date=?,probability=? WHERE id=?')->execute([$status,$score,post('value')?:null,post('expected_close_date')?:null,min(100,max(0,(int)post('probability'))),$id]);audit('update','opportunity',$id);flash('success','Opportunity updated.');}redirect('/opportunities/'.$id);}
    $notes=db()->prepare("SELECT n.*,COALESCE(NULLIF(u.display_name,''),u.username,'Former user') author FROM opportunity_notes n LEFT JOIN users u ON u.id=n.user_id WHERE n.opportunity_id=? ORDER BY n.created_at DESC");$notes->execute([$id]);$noteRows=$notes->fetchAll();
    layout($o['title'],function()use($o,$contacts,$id,$noteRows){?><h1><?=e($o['title'])?></h1><div class="grid"><div class="card"><h2>Linked contacts</h2><?php foreach($contacts as $c):?><p><a href="/contacts/<?=$c['id']?>"><?=e($c['first_name'].' '.$c['last_name'])?></a><br><span class="muted"><?=e($c['company'])?></span></p><?php endforeach?></div><div class="card"><h2>Source</h2><?php if($o['source_type']==='event'):?><p>Event: <a href="/events/<?=$o['source_event_id']?>"><?=e($o['source_event'])?></a><br><span class="muted"><?=e($o['source_event_type'])?></span></p><?php elseif($o['source_type']==='other'):?><p><?=nl2br(e($o['source_note']))?></p><?php else:?><p class="muted">No source recorded.</p><?php endif?></div></div><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><h2>Opportunity details</h2><div class="form-grid"><label>Score<select name="score"><?php foreach(list_options('opportunity_score') as $option):?><option value="<?=e($option['code'])?>" <?=$o['score']===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Status<select name="status"><?php foreach(list_options('opportunity_status') as $option):?><option value="<?=e($option['code'])?>" <?=$o['status']===$option['code']?'selected':''?>><?=e($option['label'])?></option><?php endforeach?></select></label><label>Value<input type="number" step="0.01" min="0" name="value" value="<?=e($o['value'])?>"></label></div><?php if(can('opportunities.edit')):?><button>Save opportunity</button><?php endif?></form><?php if(can('opportunities.edit')&&can_edit_record($o)):?><form class="card" method="post" action="/opportunities/<?=$id?>/delete" onsubmit="return confirm('Permanently delete this opportunity and its notes? This cannot be undone.')"><input type="hidden" name="_csrf" value="<?=csrf()?>"><h2>Delete opportunity</h2><p class="muted">This permanently removes the opportunity and its notes. Linked contacts are not deleted.</p><button class="danger">Delete opportunity</button></form><?php endif?><section class="card"><h2>Opportunity notes</h2><p class="muted">Record follow-up context, changing priorities, and other sales history.</p><?php foreach($noteRows as $note):?><div class="note"><?=nl2br(e($note['body']))?><div class="muted"><?=e($note['author'])?> · <?=e(date('M j, Y g:i A',strtotime($note['created_at'])))?></div></div><?php endforeach?><?php if(!$noteRows):?><p class="muted">No notes yet.</p><?php endif?><form method="post" action="/opportunities/<?=$id?>/notes"><input type="hidden" name="_csrf" value="<?=csrf()?>"><label>Add note<textarea name="body" rows="4" placeholder="They are focused on other priorities; follow up next quarter…" required></textarea></label><button>Add note</button></form></section><?php });exit;
}
