<?php
declare(strict_types=1);

function audit_reference_type(string $key):?string{$map=['contact_id'=>'contact','event_id'=>'event','site_id'=>'site','user_id'=>'user','owner_id'=>'user','assigned_user_id'=>'user','created_by'=>'user','tag_id'=>'tag','tag_group_id'=>'tag_group','opportunity_id'=>'opportunity','company_id'=>'company','booking_id'=>'booking','resource_id'=>'resource','quote_id'=>'quote','workflow_id'=>'workflow','page_id'=>'site_page','form_id'=>'crm_form','lead_magnet_id'=>'lead_magnet','tag_ids'=>'tag','tag_group_ids'=>'tag_group'];return $map[$key]??null;}
function audit_detail_text(?string $json,array $resolved=[]):string{
 $data=json_decode((string)$json,true);if(!is_array($data)||!$data)return 'â€”';unset($data['record_label'],$data['api_user_id']);if(!$data)return 'â€”';
 $labels=['contact_id'=>'Contact','event_id'=>'Event','site_id'=>'Site','status'=>'Status','due_at'=>'Due','message'=>'Message','enabled'=>'Enabled','decision'=>'Decision','rating'=>'Rating','source'=>'Source','channel'=>'Channel','variant'=>'Variant','campaign'=>'Campaign','recipient'=>'Recipient','provider'=>'Provider','account'=>'Account','version'=>'Version','active'=>'Active'];$parts=[];
 foreach($data as $key=>$value){$label=$labels[$key]??ucwords(str_replace('_',' ',$key));$reference=audit_reference_type((string)$key);if($reference&&is_scalar($value)&&(int)$value>0)$value=$resolved[$reference][(int)$value]??ucwords(str_replace('_',' ',$reference)).' #'.(int)$value;elseif($reference&&is_array($value))$value=implode(', ',array_map(fn($id)=>$resolved[$reference][(int)$id]??ucwords(str_replace('_',' ',$reference)).' #'.(int)$id,$value));elseif(is_bool($value))$value=$value?'Yes':'No';elseif(is_array($value))$value=implode(', ',array_map(fn($v)=>is_scalar($v)?(string)$v:json_encode($v,JSON_UNESCAPED_SLASHES),$value));elseif($value===null||$value==='')$value='â€”';$parts[]=$label.': '.$value;}
 return implode(' Â· ',$parts);
}
function audit_record_url(string $entity,?int $id):?string{if(!$id)return null;$routes=['contact'=>'/contacts/','company'=>'/companies/','opportunity'=>'/opportunities/','event'=>'/events/','booking'=>'/bookings/','site'=>'/sites/','resource'=>'/resources/','quote'=>'/sales/quotes/','user'=>'/admin/users?user_id='];return isset($routes[$entity])?$routes[$entity].$id:null;}
function audit_labels_for_rows(array $rows):array{$sources=['contact'=>['contacts',"TRIM(CONCAT(first_name,' ',last_name))"],'company'=>['companies','name'],'opportunity'=>['opportunities','title'],'event'=>['events','title'],'reminder'=>['reminders',"CONCAT(message,' â€” due ',due_at)"],'event_reminder'=>['event_reminders',"CONCAT(message,' â€” due ',due_at)"],'system_alert'=>['system_alerts',"CONCAT(message,' â€” due ',due_at)"],'booking'=>['bookings',"CONCAT(attendee_name,' â€” ',starts_at)"],'tag'=>['tags','name'],'user'=>['users',"COALESCE(NULLIF(display_name,''),username)"],'resource'=>['resources','title'],'resource_portal'=>['resource_portals','name'],'site'=>['sites','name'],'site_page'=>['site_pages','name'],'crm_form'=>['crm_forms','name'],'lead_magnet'=>['lead_magnets','title'],'email_mailbox'=>['email_mailboxes','name'],'workflow'=>['workflows','name'],'quote'=>['quotes','title']];$ids=[];foreach($rows as $row){if($row['entity_id']!==null)$ids[$row['entity_type']][]=(int)$row['entity_id'];$details=json_decode((string)$row['details_json'],true)?:[];foreach($details as $key=>$value){$type=audit_reference_type((string)$key);if(!$type)continue;foreach(is_array($value)?$value:[$value] as $id)if((int)$id>0)$ids[$type][]=(int)$id;}}$labels=[];foreach($ids as $type=>$values){if(!isset($sources[$type]))continue;[$table,$expression]=$sources[$type];foreach(array_chunk(array_values(array_unique($values)),500) as $chunk){$marks=implode(',',array_fill(0,count($chunk),'?'));$q=db()->prepare("SELECT id,$expression label FROM $table WHERE id IN ($marks)");$q->execute($chunk);foreach($q->fetchAll() as $item)$labels[$type][(int)$item['id']]=$item['label'];}}return $labels;}

if($path!=='/admin/audit')return;
if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}
$userId=(int)($_GET['user_id']??0);$action=trim((string)($_GET['action']??''));$entity=trim((string)($_GET['entity']??''));$from=trim((string)($_GET['from']??''));$to=trim((string)($_GET['to']??''));
$where=['1=1'];$params=[];
if($userId){$where[]='a.user_id=?';$params[]=$userId;}
if($action!==''){$where[]='a.action=?';$params[]=$action;}
if($entity!==''){$where[]='a.entity_type=?';$params[]=$entity;}
if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$from)){$where[]='a.created_at>=?';$params[]=$from.' 00:00:00';}
if(preg_match('/^\d{4}-\d{2}-\d{2}$/',$to)){$where[]='a.created_at<DATE_ADD(?,INTERVAL 1 DAY)';$params[]=$to.' 00:00:00';}
$sql="SELECT a.*,COALESCE(NULLIF(u.display_name,''),u.username,IF(au.name IS NOT NULL,CONCAT('API: ',au.name),'System')) actor FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id LEFT JOIN api_users au ON au.id=CAST(a.details_json->>'$.api_user_id' AS UNSIGNED) WHERE ".implode(' AND ',$where).' ORDER BY a.created_at DESC LIMIT 5000';
$stmt=db()->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();$resolved=audit_labels_for_rows($rows);$tagGroupIds=[];foreach($rows as $auditRow){$auditDetails=json_decode((string)$auditRow['details_json'],true)?:[];foreach((array)($auditDetails['tag_group_ids']??[]) as $tagGroupId)if((int)$tagGroupId>0)$tagGroupIds[]=(int)$tagGroupId;if((int)($auditDetails['tag_group_id']??0)>0)$tagGroupIds[]=(int)$auditDetails['tag_group_id'];}if($tagGroupIds){$tagGroupIds=array_values(array_unique($tagGroupIds));foreach(array_chunk($tagGroupIds,500) as $chunk){$marks=implode(',',array_fill(0,count($chunk),'?'));$q=db()->prepare("SELECT id,name FROM tag_groups WHERE id IN ($marks)");$q->execute($chunk);foreach($q->fetchAll() as $item)$resolved['tag_group'][(int)$item['id']]=$item['name'];}}
foreach($rows as &$row){$details=json_decode((string)$row['details_json'],true)?:[];$id=$row['entity_id']!==null?(int)$row['entity_id']:null;$row['record_label']=$details['record_label']??($id?($resolved[$row['entity_type']][$id]??null):null);if(!$row['record_label']&&isset($details['contact_id']))$row['record_label']='Related to '.($resolved['contact'][(int)$details['contact_id']]??'contact #'.(int)$details['contact_id']);$row['detail_text']=audit_detail_text((string)$row['details_json'],$resolved);$row['record_url']=audit_record_url((string)$row['entity_type'],$id);}unset($row);
if(($_GET['export']??'')==='csv'){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="opencrm-audit-'.date('Y-m-d').'.csv"');header('X-Content-Type-Options: nosniff');$out=fopen('php://output','wb');fputcsv($out,['Timestamp','Actor','Action','Record','Entity type','Entity ID','IP address','What changed']);foreach($rows as $r)fputcsv($out,[$r['created_at'],$r['actor'],$r['action'],$r['record_label'],$r['entity_type'],$r['entity_id'],$r['ip_address'],$r['detail_text']]);fclose($out);exit;}
$users=db()->query('SELECT id,COALESCE(NULLIF(display_name,\'\'),username) username FROM users ORDER BY username')->fetchAll();$actions=db()->query('SELECT DISTINCT action FROM audit_logs ORDER BY action')->fetchAll(PDO::FETCH_COLUMN);$entities=db()->query('SELECT DISTINCT entity_type FROM audit_logs ORDER BY entity_type')->fetchAll(PDO::FETCH_COLUMN);
layout('Audit report',function()use($rows,$users,$actions,$entities,$userId,$action,$entity,$from,$to){?>
<div class="actions"><h1 style="margin:0">Audit report</h1><span class="spacer"></span><a class="btn secondary" href="/admin/settings">Application settings</a></div>
<form class="card" method="get"><div class="form-grid"><label>User<select name="user_id"><option value="">All users and API activity</option><?php foreach($users as $u):?><option value="<?=$u['id']?>" <?=$userId==(int)$u['id']?'selected':''?>><?=e($u['username'])?></option><?php endforeach?></select></label><label>Action<select name="action"><option value="">All actions</option><?php foreach($actions as $a):?><option value="<?=e($a)?>" <?=$action===$a?'selected':''?>><?=e(ucwords(str_replace('_',' ',$a)))?></option><?php endforeach?></select></label><label>Entity type<select name="entity"><option value="">All entity types</option><?php foreach($entities as $type):?><option value="<?=e($type)?>" <?=$entity===$type?'selected':''?>><?=e(ucwords(str_replace('_',' ',$type)))?></option><?php endforeach?></select></label><div></div><label>From date<input type="date" name="from" value="<?=e($from)?>"></label><label>Through date<input type="date" name="to" value="<?=e($to)?>"></label></div><div class="actions"><button>Run report</button><button class="secondary" name="export" value="csv">Export CSV</button><a class="btn secondary" href="/admin/audit">Clear filters</a></div></form>
<div class="card"><div class="actions"><h2 style="margin:0">Activity</h2><span class="spacer"></span><span class="muted"><?=count($rows)?> records<?=count($rows)===5000?' (limit reached)':''?></span></div><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Record</th><th>IP address</th><th>What changed</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['created_at'])?></td><td><?=e($r['actor'])?></td><td><?=e(ucwords(str_replace('_',' ',$r['action'])))?></td><td><?php if($r['record_url']):?><a href="<?=e($r['record_url'])?>"><strong><?=e($r['record_label']?:ucwords(str_replace('_',' ',$r['entity_type'])))?></strong></a><?php else:?><strong><?=e($r['record_label']?:ucwords(str_replace('_',' ',$r['entity_type'])))?></strong><?php endif?><br><span class="muted"><?=e(str_replace('_',' ',$r['entity_type']))?><?=$r['entity_id']!==null?' #'.e($r['entity_id']):''?></span></td><td><?=e($r['ip_address'])?></td><td><?=e($r['detail_text'])?></td></tr><?php endforeach?></tbody></table></div>
<?php });exit;

