<?php
declare(strict_types=1);
if(!function_exists('opportunity_contacts')){function opportunity_contacts(int $opportunityId): array {$s=db()->prepare('SELECT c.* FROM contacts c JOIN opportunity_contacts oc ON oc.contact_id=c.id WHERE oc.opportunity_id=? ORDER BY c.last_name,c.first_name');$s->execute([$opportunityId]);return array_values(array_filter($s->fetchAll(),fn($c)=>contact_access((int)$c['id'])!=='hidden'));}}
if($path==='/search'){
 require_login();$q=trim((string)($_GET['q']??''));$like='%'.$q.'%';$results=['Contacts'=>[],'Companies'=>[],'Opportunities'=>[],'Events'=>[],'Notes'=>[]];
 if(mb_strlen($q)>=2){$s=db()->prepare("SELECT id,CONCAT(first_name,' ',last_name) title,CONCAT_WS(' - ',company,email) detail FROM contacts WHERE first_name LIKE ? OR last_name LIKE ? OR company LIKE ? OR email LIKE ? OR phone LIKE ? ORDER BY updated_at DESC LIMIT 20");$s->execute(array_fill(0,5,$like));$results['Contacts']=array_values(array_filter($s->fetchAll(),fn($r)=>contact_access((int)$r['id'])!=='hidden'));$s=db()->prepare('SELECT id,name title,website detail FROM companies WHERE name LIKE ? OR website LIKE ? ORDER BY updated_at DESC LIMIT 20');$s->execute([$like,$like]);$results['Companies']=$s->fetchAll();$s=db()->prepare("SELECT o.id,o.title,CONCAT(o.status,' - ',o.score) detail FROM opportunities o WHERE o.title LIKE ? OR o.source_note LIKE ? ORDER BY o.created_at DESC LIMIT 20");$s->execute([$like,$like]);$results['Opportunities']=array_values(array_filter($s->fetchAll(),fn($r)=>!empty(opportunity_contacts((int)$r['id']))));if(can('events.view')){$s=db()->prepare("SELECT id,title,CONCAT(event_type,' - ',starts_at) detail FROM events WHERE title LIKE ? OR presentation_title LIKE ? OR abstract LIKE ? ORDER BY starts_at DESC LIMIT 20");$s->execute([$like,$like,$like]);$results['Events']=$s->fetchAll();}$s=db()->prepare("SELECT n.contact_id id,CONCAT(c.first_name,' ',c.last_name) title,LEFT(n.body,180) detail FROM notes n JOIN contacts c ON c.id=n.contact_id WHERE n.body LIKE ? ORDER BY n.created_at DESC LIMIT 20");$s->execute([$like]);$results['Notes']=array_values(array_filter($s->fetchAll(),fn($r)=>contact_access((int)$r['id'])!=='hidden'));}
 $paths=['Contacts'=>'contacts','Companies'=>'companies','Opportunities'=>'opportunities','Events'=>'events','Notes'=>'contacts'];layout('Search',function()use($q,$results,$paths){?><h1>Search</h1><form class="card global-search-page" method="get"><input type="search" name="q" value="<?=e($q)?>" placeholder="Search contacts, companies, opportunities, events, and notes" autofocus required minlength="2"><button>Search</button></form><?php if($q!==''&&!array_filter($results)):?><div class="card"><p class="muted">No results found.</p></div><?php endif?><div class="grid search-results"><?php foreach($results as $group=>$rows)if($rows):?><section class="card"><h2><?=e($group)?></h2><?php foreach($rows as $row):?><a class="search-result" href="/<?=$paths[$group]?>/<?=$row['id']?>"><strong><?=e($row['title'])?></strong><span><?=e($row['detail'])?></span></a><?php endforeach?></section><?php endif?></div><?php });exit;
}
if(preg_match('#^/api/contacts/(\d+)/timeline$#',$path,$m)){
 require_permission('contacts.view');$id=(int)$m[1];contact_row($id);$items=[];$add=function(string $type,string $title,string $detail,string $when)use(&$items){$items[]=compact('type','title','detail','when');};$s=db()->prepare("SELECT n.body,n.created_at,COALESCE(u.username,'System') actor FROM notes n LEFT JOIN users u ON u.id=n.user_id WHERE n.contact_id=?");$s->execute([$id]);foreach($s->fetchAll() as $r)$add('note','Note added by '.$r['actor'],$r['body'],$r['created_at']);$s=db()->prepare('SELECT e.title,e.event_type,e.starts_at FROM event_attendees ea JOIN events e ON e.id=ea.event_id WHERE ea.contact_id=? AND ea.attended=1');$s->execute([$id]);foreach($s->fetchAll() as $r)$add('event','Attended '.$r['title'],$r['event_type'],$r['starts_at']);$s=db()->prepare('SELECT o.title,o.status,o.score,o.created_at FROM opportunity_contacts oc JOIN opportunities o ON o.id=oc.opportunity_id WHERE oc.contact_id=?');$s->execute([$id]);foreach($s->fetchAll() as $r)$add('opportunity','Opportunity: '.$r['title'],$r['status'].' - '.$r['score'],$r['created_at']);$s=db()->prepare("SELECT action,created_at FROM audit_logs WHERE entity_type='contact' AND entity_id=? ORDER BY created_at DESC");$s->execute([$id]);foreach($s->fetchAll() as $r)if($r['action']!=='create')$add('change',ucwords(str_replace('_',' ',$r['action'])).' contact','Record activity',$r['created_at']);usort($items,fn($a,$b)=>strcmp($b['when'],$a['when']));header('Content-Type: application/json');echo json_encode(array_slice($items,0,100));exit;
}
if(preg_match('#^/api/contacts/(\d+)/status$#',$path,$m)){
 require_permission('contacts.view');$c=contact_row((int)$m[1]);header('Content-Type: application/json');echo json_encode(['active'=>(bool)$c['active']]);exit;
}
if(preg_match('#^/api/contacts/(\d+)/ownership$#',$path,$m)){
 require_permission('contacts.view');$c=contact_row((int)$m[1]);$owner=null;if($c['owner_id']){$s=db()->prepare('SELECT id,username FROM users WHERE id=?');$s->execute([$c['owner_id']]);$owner=$s->fetch();}$data=['owner'=>$owner,'editable'=>(bool)(user()['is_admin']??false)];if(user()['is_admin'])$data['users']=db()->query('SELECT id,username FROM users WHERE active=1 ORDER BY username')->fetchAll();header('Content-Type: application/json');echo json_encode($data);exit;
}
if($path==='/api/admin/active-users'){if(!(user()['is_admin']??false)){http_response_code(403);exit;}header('Content-Type: application/json');echo json_encode(['users'=>db()->query('SELECT id,username FROM users WHERE active=1 ORDER BY username')->fetchAll(),'csrf'=>csrf()]);exit;}
if(preg_match('#^/contacts/(\d+)/owner$#',$path,$m)&&$method==='POST'){
 if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}verify_csrf();$id=(int)$m[1];contact_row($id);$owner=(int)post('owner_id');$s=db()->prepare('SELECT COUNT(*) FROM users WHERE id=? AND active=1');$s->execute([$owner]);if(!$s->fetchColumn()){http_response_code(422);exit('Invalid owner');}db()->prepare('UPDATE contacts SET owner_id=? WHERE id=?')->execute([$owner,$id]);audit('reassign','contact',$id,['owner_id'=>$owner]);flash('success','Contact owner updated.');redirect('/contacts/'.$id);
}
if($path==='/contacts/bulk-owner'&&$method==='POST'){
 if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}verify_csrf();$ids=array_values(array_unique(array_filter(array_map('intval',(array)post('contact_ids',[])))));$owner=(int)post('owner_id');if($ids){$placeholders=implode(',',array_fill(0,count($ids),'?'));db()->prepare("UPDATE contacts SET owner_id=? WHERE id IN ($placeholders)")->execute([$owner,...$ids]);audit('bulk_reassign','contact',null,['owner_id'=>$owner,'contact_ids'=>$ids]);}flash('success',count($ids).' contacts reassigned.');redirect('/contacts');
}
if(preg_match('#^/api/ownership/(company|opportunity|event)/(\d+)$#',$path,$m)){
 require_login();$type=$m[1];$id=(int)$m[2];$map=['company'=>['companies','contacts.view'],'opportunity'=>['opportunities','contacts.view'],'event'=>['events','events.view']];[$table,$permission]=$map[$type];require_permission($permission);$s=db()->prepare("SELECT owner_id,created_by FROM $table WHERE id=?");$s->execute([$id]);$row=$s->fetch();if(!$row){http_response_code(404);exit;}$ownerId=(int)($row['owner_id']?:$row['created_by']);$s=db()->prepare('SELECT id,username FROM users WHERE id=?');$s->execute([$ownerId]);$data=['owner'=>$s->fetch()?:null,'editable'=>(bool)(user()['is_admin']??false),'csrf'=>csrf()];if($data['editable'])$data['users']=db()->query('SELECT id,username FROM users WHERE active=1 ORDER BY username')->fetchAll();header('Content-Type: application/json');echo json_encode($data);exit;
}
if(preg_match('#^/ownership/(company|opportunity|event)/(\d+)$#',$path,$m)&&$method==='POST'){
 if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}verify_csrf();$type=$m[1];$id=(int)$m[2];$owner=(int)post('owner_id');$tables=['company'=>'companies','opportunity'=>'opportunities','event'=>'events'];$s=db()->prepare('SELECT COUNT(*) FROM users WHERE id=? AND active=1');$s->execute([$owner]);if(!$s->fetchColumn()){http_response_code(422);exit('Invalid owner');}$table=$tables[$type];$s=db()->prepare("UPDATE $table SET owner_id=? WHERE id=?");$s->execute([$owner,$id]);if(!$s->rowCount()){http_response_code(404);exit('Not found');}audit('reassign',$type,$id,['owner_id'=>$owner]);flash('success',ucfirst($type).' owner updated.');redirect('/'.($type==='company'?'companies':$type.'s').'/'.$id);
}
