<?php
declare(strict_types=1);
if($path!=='/admin/data-quality'&&$path!=='/admin/data-quality/merge')return;
if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}
if($path==='/admin/data-quality/merge'&&$method==='POST'){
 verify_csrf();$type=(string)post('type');$keep=(int)post('keep_id');$remove=(int)post('remove_id');if($keep<1||$remove<1||$keep===$remove){flash('error','Choose two different records.');redirect('/admin/data-quality');}$pdo=db();$pdo->beginTransaction();try{
  if($type==='contact'){$check=$pdo->prepare('SELECT COUNT(*) FROM contacts WHERE id IN (?,?)');$check->execute([$keep,$remove]);if((int)$check->fetchColumn()!==2)throw new RuntimeException('Contact not found.');$pdo->prepare('INSERT IGNORE INTO contact_tags(contact_id,tag_id) SELECT ?,tag_id FROM contact_tags WHERE contact_id=?')->execute([$keep,$remove]);$pdo->prepare('INSERT IGNORE INTO contact_custom_values(contact_id,custom_field_id,field_value) SELECT ?,custom_field_id,field_value FROM contact_custom_values WHERE contact_id=?')->execute([$keep,$remove]);foreach(['notes','reminders'] as $table)$pdo->prepare("UPDATE $table SET contact_id=? WHERE contact_id=?")->execute([$keep,$remove]);$pdo->prepare('INSERT IGNORE INTO event_attendees(event_id,contact_id,attended) SELECT event_id,?,attended FROM event_attendees WHERE contact_id=?')->execute([$keep,$remove]);$pdo->prepare('DELETE FROM event_attendees WHERE contact_id=?')->execute([$remove]);$pdo->prepare('INSERT IGNORE INTO opportunity_contacts(opportunity_id,contact_id) SELECT opportunity_id,? FROM opportunity_contacts WHERE contact_id=?')->execute([$keep,$remove]);$pdo->prepare('DELETE FROM opportunity_contacts WHERE contact_id=?')->execute([$remove]);$pdo->prepare('UPDATE opportunities SET contact_id=? WHERE contact_id=?')->execute([$keep,$remove]);$pdo->prepare('DELETE FROM contacts WHERE id=?')->execute([$remove]);audit('merge','contact',$keep,['merged_contact_id'=>$remove]);
  }elseif($type==='company'){$check=$pdo->prepare('SELECT COUNT(*) FROM companies WHERE id IN (?,?)');$check->execute([$keep,$remove]);if((int)$check->fetchColumn()!==2)throw new RuntimeException('Company not found.');$name=$pdo->prepare('SELECT name FROM companies WHERE id=?');$name->execute([$keep]);$pdo->prepare('UPDATE contacts SET company_id=?,company=? WHERE company_id=?')->execute([$keep,(string)$name->fetchColumn(),$remove]);$pdo->prepare('DELETE FROM companies WHERE id=?')->execute([$remove]);audit('merge','company',$keep,['merged_company_id'=>$remove]);}else throw new RuntimeException('Invalid merge type.');
  $pdo->commit();flash('success','Records merged and related activity preserved.');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();app_log('error','Data quality merge failed',['error'=>$e->getMessage()]);flash('error',$e->getMessage());}redirect('/admin/data-quality');
}
$contacts=db()->query("SELECT a.id keep_id,b.id remove_id,CONCAT(a.first_name,' ',a.last_name) keep_name,CONCAT(b.first_name,' ',b.last_name) remove_name,a.email keep_email,b.email remove_email FROM contacts a JOIN contacts b ON a.id<b.id AND ((a.email<>'' AND LOWER(a.email)=LOWER(b.email)) OR (LOWER(a.first_name)=LOWER(b.first_name) AND LOWER(a.last_name)=LOWER(b.last_name) AND LOWER(COALESCE(a.company,''))=LOWER(COALESCE(b.company,'')))) ORDER BY a.updated_at DESC LIMIT 100")->fetchAll();
$companies=db()->query("SELECT a.id keep_id,b.id remove_id,a.name keep_name,b.name remove_name FROM companies a JOIN companies b ON a.id<b.id AND LOWER(REGEXP_REPLACE(a.name,'[^a-z0-9]',''))=LOWER(REGEXP_REPLACE(b.name,'[^a-z0-9]','')) ORDER BY a.name LIMIT 100")->fetchAll();
layout('Data quality',function()use($contacts,$companies){?><div class="actions"><h1 style="margin:0">Data quality</h1><span class="spacer"></span><a class="btn secondary" href="/admin/settings">Application settings</a></div><div class="card"><h2>Suspected duplicate contacts</h2><p class="muted">Matches use email or name and company. Review both records first; tags, notes, events, opportunities, fields, and reminders are preserved.</p><table><thead><tr><th>Keep</th><th>Merge into it</th><th></th></tr></thead><tbody><?php foreach($contacts as $r):?><tr><td><a href="/contacts/<?=$r['keep_id']?>"><?=e($r['keep_name'])?></a><br><span class="muted"><?=e($r['keep_email'])?></span></td><td><a href="/contacts/<?=$r['remove_id']?>"><?=e($r['remove_name'])?></a><br><span class="muted"><?=e($r['remove_email'])?></span></td><td><?php merge_form('contact',$r)?></td></tr><?php endforeach?></tbody></table></div><div class="card"><h2>Suspected duplicate companies</h2><p class="muted">Matches ignore spaces and punctuation.</p><table><thead><tr><th>Keep</th><th>Merge into it</th><th></th></tr></thead><tbody><?php foreach($companies as $r):?><tr><td><a href="/companies/<?=$r['keep_id']?>"><?=e($r['keep_name'])?></a></td><td><a href="/companies/<?=$r['remove_id']?>"><?=e($r['remove_name'])?></a></td><td><?php merge_form('company',$r)?></td></tr><?php endforeach?></tbody></table></div><?php });exit;
function merge_form(string $type,array $r):void{?><form method="post" action="/admin/data-quality/merge" onsubmit="return confirm('Merge these records? This cannot be undone.')"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="type" value="<?=e($type)?>"><input type="hidden" name="keep_id" value="<?=$r['keep_id']?>"><input type="hidden" name="remove_id" value="<?=$r['remove_id']?>"><button class="danger">Merge</button></form><?php }
