<?php
declare(strict_types=1);
if($path==='/api/contact-views'){
 require_permission('contacts.view');$s=db()->prepare('SELECT id,name,filters_json,is_default,position FROM contact_saved_views WHERE user_id=? ORDER BY position,name');$s->execute([user()['id']]);$views=$s->fetchAll();foreach($views as &$v){$v['id']=(int)$v['id'];$v['is_default']=(bool)$v['is_default'];$v['filters']=json_decode($v['filters_json'],true)?:[];unset($v['filters_json']);}unset($v);header('Content-Type: application/json');echo json_encode(['views'=>$views,'csrf'=>csrf()]);exit;
}
if($path==='/api/contact-table'){
 require_permission('contacts.view');$ids=array_slice(array_values(array_unique(array_filter(array_map('intval',explode(',',(string)($_GET['ids']??'')))))),0,500);$records=[];if($ids){$placeholders=implode(',',array_fill(0,count($ids),'?'));$s=db()->prepare("SELECT * FROM contacts WHERE id IN ($placeholders)");$s->execute($ids);foreach($s->fetchAll() as $c)if(contact_access((int)$c['id'])!=='hidden')$records[(string)$c['id']]=['phone'=>$c['phone'],'editable'=>can('contacts.edit')&&contact_access((int)$c['id'])==='write'&&can_edit_record($c)];}header('Content-Type: application/json');echo json_encode(['records'=>$records,'csrf'=>csrf()]);exit;
}
if($path==='/contact-views'&&$method==='POST'){
 require_permission('contacts.view');verify_csrf();$action=(string)post('action');$id=(int)post('view_id');$uid=(int)user()['id'];
 if($action==='save'){$name=trim((string)post('name'));if($name===''){flash('error','View name is required.');redirect('/contacts');}$filters=[];foreach(['q','tag','view','contact_status','updated_older_days','columns'] as $key){$value=post($key);if($value!==''&&$value!==null)$filters[$key]=$value;}$isDefault=post('is_default')?1:0;if($isDefault)db()->prepare('UPDATE contact_saved_views SET is_default=0 WHERE user_id=?')->execute([$uid]);db()->prepare('INSERT INTO contact_saved_views(user_id,name,filters_json,is_default) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE filters_json=VALUES(filters_json),is_default=VALUES(is_default)')->execute([$uid,$name,json_encode($filters),$isDefault]);audit('save_view','contact_view',null,['name'=>$name]);}
 elseif($action==='default'){$s=db()->prepare('SELECT COUNT(*) FROM contact_saved_views WHERE id=? AND user_id=?');$s->execute([$id,$uid]);if($s->fetchColumn()){db()->prepare('UPDATE contact_saved_views SET is_default=(id=?) WHERE user_id=?')->execute([$id,$uid]);audit('default_view','contact_view',$id);}}
 elseif($action==='delete'){$s=db()->prepare('DELETE FROM contact_saved_views WHERE id=? AND user_id=?');$s->execute([$id,$uid]);audit('delete_view','contact_view',$id);}
 flash('success','Contact views updated.');redirect('/contacts');
}
if(preg_match('#^/api/contacts/(\d+)/(relationships|history)$#',$path,$m)){
 require_permission('contacts.view');$id=(int)$m[1];$c=contact_row($id);header('Content-Type: application/json');
 if($m[2]==='history'){$s=db()->prepare("SELECT ch.*,COALESCE(u.username,'System') actor FROM contact_field_changes ch LEFT JOIN users u ON u.id=ch.user_id WHERE ch.contact_id=? ORDER BY ch.created_at DESC LIMIT 200");$s->execute([$id]);echo json_encode(['changes'=>$s->fetchAll()]);exit;}
 $s=db()->prepare('SELECT cr.id,cr.relationship_type,cr.notes,c.id contact_id,c.first_name,c.last_name,c.company FROM contact_relationships cr JOIN contacts c ON c.id=cr.related_contact_id WHERE cr.contact_id=? UNION SELECT cr.id,cr.relationship_type,cr.notes,c.id contact_id,c.first_name,c.last_name,c.company FROM contact_relationships cr JOIN contacts c ON c.id=cr.contact_id WHERE cr.related_contact_id=? ORDER BY last_name,first_name');$s->execute([$id,$id]);$related=array_values(array_filter($s->fetchAll(),fn($r)=>contact_access((int)$r['contact_id'])!=='hidden'));$coworkers=[];if($c['company_id']){$s=db()->prepare('SELECT id,first_name,last_name,job_title,company FROM contacts WHERE company_id=? AND id<>? AND active=1 ORDER BY last_name,first_name');$s->execute([$c['company_id'],$id]);$coworkers=array_values(array_filter($s->fetchAll(),fn($r)=>contact_access((int)$r['id'])!=='hidden'));}$candidates=array_values(array_filter(db()->query('SELECT id,first_name,last_name,company FROM contacts WHERE active=1 ORDER BY last_name,first_name LIMIT 5000')->fetchAll(),fn($r)=>(int)$r['id']!==$id&&contact_access((int)$r['id'])!=='hidden'));echo json_encode(['related'=>$related,'coworkers'=>$coworkers,'candidates'=>$candidates,'editable'=>can('contacts.edit')&&can_edit_record($c),'csrf'=>csrf()]);exit;
}
if(preg_match('#^/contacts/(\d+)/relationships$#',$path,$m)&&$method==='POST'){
 require_permission('contacts.edit');verify_csrf();$id=(int)$m[1];$c=contact_row($id);require_record_edit($c);$related=(int)post('related_contact_id');if($related===$id||contact_access($related)==='hidden'){http_response_code(422);exit('Invalid related contact');}$type=trim((string)post('relationship_type'))?:'Related contact';db()->prepare('INSERT INTO contact_relationships(contact_id,related_contact_id,relationship_type,notes,created_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE relationship_type=VALUES(relationship_type),notes=VALUES(notes)')->execute([$id,$related,$type,trim((string)post('notes'))?:null,user()['id']]);audit('relate','contact',$id,['related_contact_id'=>$related,'type'=>$type]);redirect('/contacts/'.$id);
}
if(preg_match('#^/contacts/(\d+)/archive$#',$path,$m)&&$method==='POST'){
 require_permission('contacts.edit');verify_csrf();$id=(int)$m[1];$c=contact_row($id);require_record_edit($c);db()->prepare('UPDATE contacts SET active=0 WHERE id=?')->execute([$id]);$after=$c;$after['active']=0;record_contact_changes($id,$c,$after);audit('archive','contact',$id);flash('success','Contact archived.');redirect('/contacts');
}
