<?php
declare(strict_types=1);
if($path==='/forgot-password'){
 if($method==='POST'){
  verify_csrf();$identity=mb_strtolower(trim((string)post('identity')));$ip=(string)($_SERVER['REMOTE_ADDR']??'');$allowed=true;
  try{$rate=db()->prepare('SELECT COUNT(*) FROM password_reset_tokens WHERE created_at>=DATE_SUB(NOW(),INTERVAL 1 HOUR) AND requested_ip=?');$rate->execute([$ip]);$allowed=(int)$rate->fetchColumn()<5;}catch(Throwable $e){$allowed=false;}
  if($allowed&&$identity!==''){$q=db()->prepare('SELECT id,username,email FROM users WHERE active=1 AND email IS NOT NULL AND email<>\'\' AND (LOWER(email)=? OR LOWER(username)=?) LIMIT 1');$q->execute([$identity,$identity]);if($account=$q->fetch()){$raw=bin2hex(random_bytes(32));$hash=hash('sha256',$raw);db()->prepare('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=? AND used_at IS NULL')->execute([$account['id']]);db()->prepare('INSERT INTO password_reset_tokens(user_id,token_hash,requested_ip,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 60 MINUTE))')->execute([$account['id'],$hash,$ip]);$url=rtrim((string)config('url'),'/').'/reset-password?token='.$raw;$body="A password reset was requested for your ".app_setting('app_name','OpenCRM')." account.\n\nReset your password within 60 minutes:\n$url\n\nIf you did not request this, you can ignore this message. Your password has not changed.";try{crm_send_email($account['email'],'Reset your '.app_setting('app_name','OpenCRM').' password',$body,true);app_log('info','Password reset email sent',['user_id'=>(int)$account['id']]);}catch(Throwable $e){app_log('error','Password reset email failed',['user_id'=>(int)$account['id'],'error'=>$e->getMessage()]);}}}
  flash('success','If an active account matches that information, a password reset link has been emailed.');redirect('/forgot-password');
 }
 layout('Forgot password',function(){?><div class="card login"><h1>Reset your password</h1><p>Enter your username or account email. If it matches an active account, weâ€™ll send a link that expires in 60 minutes.</p><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><label>Username or email<input name="identity" autocomplete="username" required autofocus></label><button>Send reset link</button></form><p><a href="/login">Return to sign in</a></p></div><?php });exit;
}
if($path==='/reset-password'){
 $raw=(string)($_GET['token']??post('token'));$valid=preg_match('/^[a-f0-9]{64}$/',$raw);$row=null;if($valid){$q=db()->prepare('SELECT t.*,u.username FROM password_reset_tokens t JOIN users u ON u.id=t.user_id AND u.active=1 WHERE t.token_hash=? AND t.used_at IS NULL AND t.expires_at>NOW() LIMIT 1');$q->execute([hash('sha256',$raw)]);$row=$q->fetch()?:null;}
 if($method==='POST'){verify_csrf();if(!$row){flash('error','That reset link is invalid or has expired. Request a new one.');redirect('/forgot-password');}$password=(string)post('password');if(strlen($password)<12)flash('error','Use at least 12 characters.');elseif($password!==(string)post('confirm'))flash('error','Passwords do not match.');else{db()->beginTransaction();try{db()->prepare('UPDATE users SET password_hash=?,force_password_change=0 WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$row['user_id']]);db()->prepare('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=? AND used_at IS NULL')->execute([$row['user_id']]);db()->commit();session_regenerate_id(true);audit('self_service_password_reset','user',(int)$row['user_id']);flash('success','Your password has been updated. You can now sign in.');redirect('/login');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}}
 }
 if(!$row){http_response_code(400);layout('Reset link expired',function(){?><div class="card login"><h1>Reset link unavailable</h1><p>This link is invalid, expired, or has already been used.</p><a class="btn" href="/forgot-password">Request a new link</a></div><?php });exit;}
 layout('Choose a new password',function()use($raw,$row){?><div class="card login"><h1>Choose a new password</h1><p>Resetting the password for <strong><?=e($row['username'])?></strong>.</p><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="token" value="<?=e($raw)?>"><label>New password<input type="password" name="password" minlength="12" autocomplete="new-password" required autofocus></label><label>Confirm password<input type="password" name="confirm" minlength="12" autocomplete="new-password" required></label><button>Update password</button></form></div><?php });exit;
}

