<?php
declare(strict_types=1);
function csv_download(string $name,array $headers,array $rows): never {header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$name.'"');header('X-Content-Type-Options: nosniff');$out=fopen('php://output','wb');fputcsv($out,$headers);foreach($rows as $row)fputcsv($out,$row);fclose($out);exit;}
if($path==='/api/admin/custom-fields'){if(!(user()['is_admin']??false)){http_response_code(403);exit;}header('Content-Type: application/json');echo json_encode(array_map(fn($f)=>['id'=>(int)$f['id'],'required'=>(bool)$f['required'],'validation_pattern'=>$f['validation_pattern']],custom_field_definitions(false)));exit;}
if($path==='/contacts/export'){
 require_permission('contacts.view');$where=['1=1'];$params=[];$q=trim((string)($_GET['q']??''));if($q!==''){$where[]='(c.first_name LIKE ? OR c.last_name LIKE ? OR c.company LIKE ? OR c.email LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like,$like);}$status=(string)($_GET['contact_status']??($q!==''?'all':'active'));if($status==='active')$where[]='c.active=1';elseif($status==='inactive')$where[]='c.active=0';if(!empty($_GET['tag'])){$where[]='ct.tag_id=?';$params[]=(int)$_GET['tag'];}$older=max(0,min(3650,(int)($_GET['updated_older_days']??0)));if($older)$where[]="c.updated_at<DATE_SUB(NOW(),INTERVAL $older DAY)";if(($_GET['view']??'mine')!=='all'){$where[]='COALESCE(c.owner_id,c.created_by)=?';$params[]=user()['id'];}$sql="SELECT c.*,GROUP_CONCAT(DISTINCT t.name ORDER BY t.name SEPARATOR ', ') tags FROM contacts c LEFT JOIN contact_tags ct ON ct.contact_id=c.id LEFT JOIN tags t ON t.id=ct.tag_id WHERE ".implode(' AND ',$where).' GROUP BY c.id ORDER BY c.last_name,c.first_name';$contactStmt=db()->prepare($sql);$contactStmt->execute($params);$rows=[];$noteStmt=db()->prepare("SELECT n.created_at,n.body,COALESCE(u.username,'System') author FROM notes n LEFT JOIN users u ON u.id=n.user_id WHERE n.contact_id=? ORDER BY n.created_at");foreach($contactStmt->fetchAll() as $c)if(contact_access((int)$c['id'])!=='hidden'){$noteStmt->execute([$c['id']]);$notes=implode("\n\n",array_map(fn($n)=>'['.$n['created_at'].'] '.$n['author'].': '.$n['body'],$noteStmt->fetchAll()));$rows[]=[$c['first_name'],$c['last_name'],$c['company'],$c['job_title'],$c['email'],$c['phone'],$c['website'],$c['address'],$c['tags'],$notes,$c['active']?'Active':'Inactive',$c['created_at'],$c['updated_at']];}csv_download('contacts-'.date('Y-m-d').'.csv',['First name','Last name','Company','Job title','Email','Phone','Website','Address','Tags','Notes','Status','Created','Updated'],$rows);
}
if(preg_match('#^/contacts/(\d+)/export$#',$path,$m)){
 require_permission('contacts.view');$id=(int)$m[1];$c=contact_row($id);$rows=[['Contact','Name',$c['first_name'].' '.$c['last_name']],['Contact','Company',$c['company']],['Contact','Email',$c['email']],['Contact','Phone',$c['phone']],['Contact','Tags',implode(', ',array_column(contact_tags($id),'name'))]];$s=db()->prepare('SELECT created_at,body FROM notes WHERE contact_id=? ORDER BY created_at');$s->execute([$id]);foreach($s->fetchAll() as $n)$rows[]=['Note',$n['created_at'],$n['body']];$s=db()->prepare('SELECT o.title,o.status,o.score,o.value FROM opportunities o JOIN opportunity_contacts oc ON oc.opportunity_id=o.id WHERE oc.contact_id=?');$s->execute([$id]);foreach($s->fetchAll() as $o)$rows[]=['Opportunity',$o['title'],$o['status'].' / '.$o['score'].' / '.$o['value']];csv_download('contact-'.$id.'-'.date('Y-m-d').'.csv',['Section','Field / Date','Value'],$rows);
}
if($path==='/reports/export'){
 require_permission('reports.view');$params=[];$where=report_contact_where($params);$stmt=db()->prepare("SELECT CONCAT(c.first_name,' ',c.last_name),c.company,c.email,c.phone,GROUP_CONCAT(DISTINCT t.name ORDER BY t.name SEPARATOR ', '),c.created_at,c.updated_at FROM contacts c LEFT JOIN contact_tags ct ON ct.contact_id=c.id LEFT JOIN tags t ON t.id=ct.tag_id WHERE ".implode(' AND ',$where).' GROUP BY c.id ORDER BY c.updated_at DESC');$stmt->execute($params);csv_download('report-'.date('Y-m-d').'.csv',['Contact','Company','Email','Phone','Tags','Created','Updated'],$stmt->fetchAll(PDO::FETCH_NUM));
}
if($path==='/opportunities/board'){
 require_permission('contacts.view');$statuses=list_options('opportunity_status');$rows=db()->query("SELECT o.*,COALESCE(NULLIF(u.display_name,''),u.username) owner FROM opportunities o LEFT JOIN users u ON u.id=o.owner_id WHERE o.active=1 ORDER BY o.created_at DESC")->fetchAll();$by=[];foreach($rows as $row)$by[$row['status']][]=$row;
 layout('Pipeline board',function()use($statuses,$by){?><div class="actions"><h1 style="margin:0">Pipeline board</h1><span class="spacer"></span><a class="btn secondary" href="/opportunities">Table view</a><a class="btn" href="/opportunities/new">Add opportunity</a></div><div class="pipeline-board"><?php foreach($statuses as $status):$items=$by[$status['code']]??[];?><section class="pipeline-column"><h2><?=e($status['label'])?> <span class="muted"><?=count($items)?> · $<?=number_format(array_sum(array_column($items,'value')),2)?></span></h2><?php foreach($items as $o):?><article class="pipeline-card"><a href="/opportunities/<?=$o['id']?>"><strong><?=e($o['title'])?></strong></a><div>$<?=number_format((float)$o['value'],2)?> · <?=e($o['probability']??0)?>%</div><div class="muted"><?=e($o['owner']?:'Unassigned')?> · <?=e($o['expected_close_date']?:'No close date')?> · <?=floor((time()-strtotime($o['created_at']))/86400)?> days</div><?php if(can('contacts.edit')&&can_edit_record($o)):?><form method="post" action="/opportunities/<?=$o['id']?>/stage"><input type="hidden" name="_csrf" value="<?=csrf()?>"><select name="status" onchange="this.form.submit()"><?php foreach($statuses as $choice):?><option value="<?=e($choice['code'])?>" <?=$choice['code']===$o['status']?'selected':''?>><?=e($choice['label'])?></option><?php endforeach?></select></form><?php endif?></article><?php endforeach?></section><?php endforeach?></div><?php });exit;
}
if(preg_match('#^/opportunities/(\d+)/stage$#',$path,$m)&&$method==='POST'){
 require_permission('contacts.edit');verify_csrf();$s=db()->prepare('SELECT * FROM opportunities WHERE id=?');$s->execute([(int)$m[1]]);$o=$s->fetch();if(!$o){http_response_code(404);exit('Not found');}require_record_edit($o);$status=post('status');if(in_array($status,option_codes('opportunity_status'),true)){db()->prepare("UPDATE opportunities SET status=?,closed_at=IF(? IN ('won','lost'),COALESCE(closed_at,NOW()),NULL) WHERE id=?")->execute([$status,$status,$o['id']]);audit('pipeline_move','opportunity',(int)$o['id'],['status'=>$status]);}redirect('/opportunities/board');
}
if($path==='/admin/health'){
 if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}$uploadDir=dirname(__DIR__).'/storage/uploads';$bytes=0;$files=0;foreach(new DirectoryIterator($uploadDir) as $file)if($file->isFile()&&!$file->isDot()){$bytes+=$file->getSize();$files++;}$dbSize=(int)db()->query("SELECT COALESCE(SUM(data_length+index_length),0) FROM information_schema.TABLES WHERE table_schema=DATABASE()")->fetchColumn();$errors=(int)db()->query("SELECT COUNT(*) FROM application_logs WHERE level='error' AND created_at>=DATE_SUB(NOW(),INTERVAL 24 HOUR)")->fetchColumn();$backups=glob(dirname(__DIR__).'/storage/backups/*')?:[];$disk=@disk_free_space(dirname(__DIR__));
 layout('System health',function()use($bytes,$files,$dbSize,$errors,$backups,$disk){?><div class="actions"><h1 style="margin:0">System health</h1><span class="spacer"></span><a class="btn secondary" href="/admin/settings">Settings</a></div><div class="grid"><div class="card"><div class="metric"><?=number_format($dbSize/1048576,1)?> MB</div>Database size</div><div class="card"><div class="metric"><?=number_format($bytes/1048576,1)?> MB</div><?=$files?> uploaded files</div><div class="card"><div class="metric"><?=number_format((float)$disk/1073741824,1)?> GB</div>Server disk available</div><div class="card"><div class="metric"><?=$errors?></div>Errors in last 24 hours</div><div class="card"><div class="metric"><?=count($backups)?></div>Backup files detected</div></div><div class="card"><h2>Checks</h2><p>Database: <strong>Connected</strong></p><p>Uploads directory: <strong><?=is_writable($uploadDir)?'Writable':'Not writable'?></strong></p><p>Latest backup: <strong><?=$backups?e(date('Y-m-d H:i',max(array_map('filemtime',$backups)))):'No local backup detected'?></strong></p><p class="muted">Backups should be copied off-server and restore-tested regularly.</p></div><?php });exit;
}
