<?php
declare(strict_types=1);

if($path!=='/admin/dropdowns')return;
if(!(user()['is_admin']??false)){http_response_code(403);exit('Forbidden');}
$listKey=(string)($_GET['list']??'opportunity_score');$allowedLists=['opportunity_score','opportunity_status','opportunity_source','event_type'];if(!in_array($listKey,$allowedLists,true))$listKey='opportunity_score';
$stmt=db()->prepare('SELECT * FROM option_lists WHERE list_key=?');$stmt->execute([$listKey]);$list=$stmt->fetch();if(!$list){http_response_code(500);exit('Dropdown lists have not been migrated.');}
if($method==='POST'){
    verify_csrf();$action=(string)post('action');
    if($action==='create'){$label=trim((string)post('label'));$code=trim((string)post('code'));if($code==='')$code=strtolower(trim((string)preg_replace('/[^a-z0-9]+/i','_',$label),'_'));if($label===''||$code===''||!preg_match('/^[a-z0-9_]{1,80}$/',$code)){flash('error','Enter a label and a code using lowercase letters, numbers, or underscores.');redirect('/admin/dropdowns?list='.$listKey);}try{db()->prepare('INSERT INTO option_values(list_id,code,label,color,position) VALUES(?,?,?,?,?)')->execute([$list['id'],$code,$label,post('color')?:null,(int)post('position')]);audit('create','dropdown_option',(int)db()->lastInsertId(),['list'=>$listKey]);flash('success','Dropdown option added.');}catch(PDOException $e){if(($e->errorInfo[1]??0)===1062)flash('error','That option code already exists.');else throw $e;}}
    elseif($action==='update'){$id=(int)post('option_id');$color=post('color')?:null;if($color&&!preg_match('/^#[0-9a-fA-F]{6}$/',$color))$color=null;db()->prepare('UPDATE option_values SET label=?,color=?,position=?,active=? WHERE id=? AND list_id=?')->execute([trim((string)post('label')),$color,(int)post('position'),post('active')?1:0,$id,$list['id']]);audit('update','dropdown_option',$id,['list'=>$listKey]);flash('success','Dropdown option updated.');}
    redirect('/admin/dropdowns?list='.$listKey);
}
$options=list_options($listKey,true);$lists=db()->query('SELECT * FROM option_lists ORDER BY name')->fetchAll();
layout('Dropdown lists',function()use($list,$listKey,$lists,$options){?><div class="actions"><h1 style="margin:0">Dropdown lists</h1><span class="spacer"></span><a class="btn secondary" href="/admin/settings">Application settings</a></div><div class="card"><nav class="actions"><?php foreach($lists as $l):?><a class="btn <?=$l['list_key']===$listKey?'':'secondary'?>" href="/admin/dropdowns?list=<?=e($l['list_key'])?>"><?=e($l['name'])?></a><?php endforeach?></nav><p class="muted"><?=e($list['description'])?></p></div><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="create"><h2>Add option</h2><div class="form-grid"><label>Display label<input name="label" required maxlength="120"></label><label>Code <span class="muted">(optional; generated from label)</span><input name="code" pattern="[a-z0-9_]+" maxlength="80"></label><label>Color <span class="muted">(optional)</span><input type="color" name="color" value="#546e7a"></label><label>Sort position<input type="number" name="position" value="100"></label></div><button>Add option</button></form><div class="card"><h2><?=e($list['name'])?></h2><table><thead><tr><th>Label</th><th>Code</th><th>Color</th><th>Order</th><th>Available</th><th></th></tr></thead><tbody><?php foreach($options as $o):?><tr><td><form id="option-<?=$o['id']?>" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="update"><input type="hidden" name="option_id" value="<?=$o['id']?>"><input name="label" value="<?=e($o['label'])?>" required></form></td><td><code><?=e($o['code'])?></code></td><td><input form="option-<?=$o['id']?>" style="width:54px;height:42px" type="color" name="color" value="<?=e($o['color']?:'#546e7a')?>"></td><td><input form="option-<?=$o['id']?>" style="width:90px" type="number" name="position" value="<?=$o['position']?>"></td><td><label style="margin:0"><input form="option-<?=$o['id']?>" style="width:auto" type="checkbox" name="active" value="1" <?=$o['active']?'checked':''?>> Active</label></td><td><button form="option-<?=$o['id']?>">Save</button></td></tr><?php endforeach?></tbody></table><p class="muted">Deactivate options to hide them from new entries. Existing records keep their historical value.</p></div><?php });exit;
