<?php
declare(strict_types=1);

function event_presenter_contacts(): array {return array_values(array_filter(db()->query('SELECT id,first_name,last_name,company FROM contacts WHERE active=1 ORDER BY last_name,first_name')->fetchAll(),fn($c)=>contact_access((int)$c['id'])!=='hidden'));}
function event_presenter_choices(): array {return ['users'=>db()->query("SELECT id,COALESCE(NULLIF(display_name,''),username) name FROM users WHERE active=1 ORDER BY name")->fetchAll(),'contacts'=>event_presenter_contacts()];}
function event_presenter_values(int $eventId): array {$s=db()->prepare("SELECT CONCAT(presenter_type,':',presenter_id) FROM event_presenters WHERE event_id=? ORDER BY presenter_type,presenter_id");$s->execute([$eventId]);return $s->fetchAll(PDO::FETCH_COLUMN);}
function sync_event_presenters(int $eventId,array $values): void {$parsed=[];foreach($values as $value)if(preg_match('/^(user|contact):(\d+)$/',(string)$value,$m)){$type=$m[1];$id=(int)$m[2];if($type==='contact'&&contact_access($id)==='hidden')continue;$table=$type==='user'?'users':'contacts';$s=db()->prepare("SELECT COUNT(*) FROM $table WHERE id=?".($type==='user'?' AND active=1':''));$s->execute([$id]);if($s->fetchColumn())$parsed[$type.':'.$id]=[$type,$id];}db()->prepare('DELETE FROM event_presenters WHERE event_id=?')->execute([$eventId]);$insert=db()->prepare('INSERT INTO event_presenters(event_id,presenter_type,presenter_id) VALUES(?,?,?)');foreach($parsed as [$type,$id])$insert->execute([$eventId,$type,$id]);}
function event_slides(array $event): array {$slides=$event['slides_path']??null;$original=$event['slides_original_name']??null;if(isset($_FILES['slides'])&&$_FILES['slides']['error']!==UPLOAD_ERR_NO_FILE){$f=$_FILES['slides'];$allowed=['application/pdf'=>'pdf','application/vnd.ms-powerpoint'=>'ppt','application/vnd.openxmlformats-officedocument.presentationml.presentation'=>'pptx'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if($f['error']!==UPLOAD_ERR_OK||$f['size']>config('upload_max')||!isset($allowed[$mime]))throw new InvalidArgumentException('Slides must be a PDF, PPT, or PPTX within the upload limit.');$slides=bin2hex(random_bytes(20)).'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],dirname(__DIR__).'/storage/uploads/'.$slides))throw new RuntimeException('Upload failed.');$original=basename($f['name']);}return [$slides,$original];}
function event_presenter_form(array $event,array $choices,array $selected,bool $editing): void {$id=(int)($event['id']??0);?><div class="actions"><h1 style="margin:0"><?=$editing?'Edit event':'New event'?></h1><?php if($editing):?><span class="spacer"></span><a class="btn secondary" href="/events/<?=$id?>">Cancel</a><?php endif?></div><form class="card" method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=csrf()?>"><div class="form-grid"><label>Event name<input name="title" value="<?=e($event['title']??'')?>" required></label><label>Type<select name="event_type"><?php foreach(list_options('event_type') as $o):?><option value="<?=e($o['code'])?>" <?=($event['event_type']??'')===$o['code']?'selected':''?>><?=e($o['label'])?></option><?php endforeach?></select></label><label>Date and time<input type="datetime-local" name="starts_at" value="<?=e(isset($event['starts_at'])?str_replace(' ','T',substr($event['starts_at'],0,16)):'')?>" required></label><label><?=$editing?'Replace slides':'Slides'?><input type="file" name="slides" accept=".pdf,.ppt,.pptx"><?php if($editing):?><span class="muted"><?=e($event['slides_original_name']?:'No slides uploaded')?></span><?php endif?></label><label>Presentation title<input name="presentation_title" value="<?=e($event['presentation_title']??'')?>"></label><label>Webinar booking URL<input type="url" name="booking_url" value="<?=e($event['booking_url']??'')?>"></label><label>Conference URL<input type="url" name="conference_url" value="<?=e($event['conference_url']??'')?>"></label><label>Conference address<textarea name="venue_address"><?=e($event['venue_address']??'')?></textarea></label><label class="full">Presenters and co-presenters<select name="presenters[]" multiple size="10"><optgroup label="CRM users"><?php foreach($choices['users'] as $person):$value='user:'.$person['id'];?><option value="<?=$value?>" <?=in_array($value,$selected,true)?'selected':''?>><?=e($person['name'])?> (CRM user)</option><?php endforeach?></optgroup><optgroup label="Contacts"><?php foreach($choices['contacts'] as $person):$value='contact:'.$person['id'];?><option value="<?=$value?>" <?=in_array($value,$selected,true)?'selected':''?>><?=e($person['last_name'].', '.$person['first_name'].($person['company']?' — '.$person['company']:''))?></option><?php endforeach?></optgroup></select><span class="muted">Choose any combination of CRM users and contacts. Use Ctrl/Cmd to select multiple presenters.</span></label><label class="full">Other presenter name <span class="muted">(optional, for someone not in the CRM)</span><input name="presenter_name" value="<?=e($event['presenter_name']??'')?>"></label><label class="full">Abstract<textarea name="abstract" rows="7"><?=e($event['abstract']??'')?></textarea></label></div><button><?=$editing?'Save event':'Create event'?></button></form><?php }

if($path==='/events/new'){
    require_permission('events.edit');$event=[];if($method==='POST'){verify_csrf();$type=(string)post('event_type');if(!in_array($type,option_codes('event_type'),true)){flash('error','Choose a valid event type.');redirect('/events/new');}try{[$slides,$original]=event_slides([]);db()->beginTransaction();db()->prepare('INSERT INTO events(title,event_type,starts_at,presentation_title,abstract,booking_url,conference_url,venue_address,slides_path,slides_original_name,presenter_name,created_by,owner_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([trim(post('title')),$type,post('starts_at'),trim(post('presentation_title'))?:null,trim(post('abstract'))?:null,trim(post('booking_url'))?:null,trim(post('conference_url'))?:null,trim(post('venue_address'))?:null,$slides,$original,trim(post('presenter_name'))?:null,user()['id'],user()['id']]);$id=(int)db()->lastInsertId();sync_event_presenters($id,(array)post('presenters',[]));audit('create','event',$id,['presenters'=>count((array)post('presenters',[]))]);db()->commit();redirect('/events/'.$id);}catch(InvalidArgumentException $e){if(db()->inTransaction())db()->rollBack();flash('error',$e->getMessage());redirect('/events/new');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}}layout('New event',fn()=>event_presenter_form([],event_presenter_choices(),[],false));exit;
}
if(preg_match('#^/events/(\d+)/edit$#',$path,$m)){
    require_permission('events.edit');$id=(int)$m[1];$s=db()->prepare('SELECT * FROM events WHERE id=?');$s->execute([$id]);$event=$s->fetch();if(!$event){http_response_code(404);exit('Event not found');}require_record_edit($event);if($method==='POST'){verify_csrf();$type=(string)post('event_type');if(!in_array($type,option_codes('event_type'),true)){flash('error','Choose a valid event type.');redirect('/events/'.$id.'/edit');}try{[$slides,$original]=event_slides($event);db()->beginTransaction();db()->prepare('UPDATE events SET title=?,event_type=?,starts_at=?,presentation_title=?,abstract=?,booking_url=?,conference_url=?,venue_address=?,slides_path=?,slides_original_name=?,presenter_contact_id=NULL,presenter_name=? WHERE id=?')->execute([trim(post('title')),$type,post('starts_at'),trim(post('presentation_title'))?:null,trim(post('abstract'))?:null,trim(post('booking_url'))?:null,trim(post('conference_url'))?:null,trim(post('venue_address'))?:null,$slides,$original,trim(post('presenter_name'))?:null,$id]);sync_event_presenters($id,(array)post('presenters',[]));audit('update','event',$id,['presenters'=>count((array)post('presenters',[]))]);db()->commit();flash('success','Event updated.');redirect('/events/'.$id);}catch(InvalidArgumentException $e){if(db()->inTransaction())db()->rollBack();flash('error',$e->getMessage());redirect('/events/'.$id.'/edit');}catch(Throwable $e){if(db()->inTransaction())db()->rollBack();throw $e;}}$selected=event_presenter_values($id);if($event['presenter_contact_id'])$selected[]='contact:'.$event['presenter_contact_id'];layout('Edit event',fn()=>event_presenter_form($event,event_presenter_choices(),array_values(array_unique($selected)),true));exit;
}

if(preg_match('#^/api/events/(\d+)/presenters$#',$path,$m)){
    require_permission('events.view');$id=(int)$m[1];$s=db()->prepare('SELECT * FROM events WHERE id=?');$s->execute([$id]);$event=$s->fetch();if(!$event){http_response_code(404);exit;}
    $s=db()->prepare("SELECT ep.id,ep.presenter_type,ep.presenter_id,CASE WHEN ep.presenter_type='user' THEN COALESCE(NULLIF(u.display_name,''),u.username) ELSE CONCAT(c.first_name,' ',c.last_name) END name,CASE WHEN ep.presenter_type='contact' THEN c.company ELSE 'CRM user' END detail FROM event_presenters ep LEFT JOIN users u ON ep.presenter_type='user' AND u.id=ep.presenter_id LEFT JOIN contacts c ON ep.presenter_type='contact' AND c.id=ep.presenter_id WHERE ep.event_id=? ORDER BY name");$s->execute([$id]);$presenters=array_values(array_filter($s->fetchAll(),fn($p)=>$p['presenter_type']!=='contact'||contact_access((int)$p['presenter_id'])!=='hidden'));
    if($event['presenter_contact_id']&&!array_filter($presenters,fn($p)=>$p['presenter_type']==='contact'&&(int)$p['presenter_id']===(int)$event['presenter_contact_id'])){$c=db()->prepare("SELECT id,CONCAT(first_name,' ',last_name) name,company detail FROM contacts WHERE id=?");$c->execute([$event['presenter_contact_id']]);if($legacy=$c->fetch())$presenters[]=['id'=>0,'presenter_type'=>'contact','presenter_id'=>$legacy['id'],'name'=>$legacy['name'],'detail'=>$legacy['detail']];}
    $users=db()->query("SELECT id,COALESCE(NULLIF(display_name,''),username) name FROM users WHERE active=1 ORDER BY name")->fetchAll();$contacts=event_presenter_contacts();
    header('Content-Type: application/json');echo json_encode(['presenters'=>$presenters,'users'=>$users,'contacts'=>$contacts,'editable'=>can('events.edit')&&can_edit_record($event),'csrf'=>csrf()]);exit;
}
if(preg_match('#^/events/(\d+)/presenters$#',$path,$m)&&$method==='POST'){
    require_permission('events.edit');verify_csrf();$id=(int)$m[1];$s=db()->prepare('SELECT * FROM events WHERE id=?');$s->execute([$id]);$event=$s->fetch();if(!$event){http_response_code(404);exit('Event not found');}require_record_edit($event);
    if(post('action')==='remove'){$presenterId=(int)post('presenter_row_id');db()->prepare('DELETE FROM event_presenters WHERE id=? AND event_id=?')->execute([$presenterId,$id]);audit('remove_presenter','event',$id,['presenter_row_id'=>$presenterId]);}
    else{$insert=db()->prepare('INSERT IGNORE INTO event_presenters(event_id,presenter_type,presenter_id) VALUES(?,?,?)');$added=0;foreach((array)post('presenters',[]) as $value){if(!preg_match('/^(user|contact):(\d+)$/',(string)$value,$parts))continue;$type=$parts[1];$personId=(int)$parts[2];if($type==='user'){$check=db()->prepare('SELECT COUNT(*) FROM users WHERE id=? AND active=1');$check->execute([$personId]);}else{$check=db()->prepare('SELECT COUNT(*) FROM contacts WHERE id=?');$check->execute([$personId]);if(contact_access($personId)==='hidden')continue;}if($check->fetchColumn()){$insert->execute([$id,$type,$personId]);$added++;}}audit('add_presenters','event',$id,['count'=>$added]);}
    redirect('/events/'.$id);
}
