<?php
declare(strict_types=1);
if($path==='/api/opportunity-statuses'){require_permission('contacts.view');header('Content-Type: application/json');echo json_encode(['statuses'=>array_map(fn($s)=>['code'=>$s['code'],'label'=>$s['label']],list_options('opportunity_status')),'csrf'=>csrf()]);exit;}
if($path!=='/partner-sales')return;
$me=user();$accessStmt=db()->prepare('SELECT partner_sales_access FROM users WHERE id=?');$accessStmt->execute([$me['id']]);
if(!($me['is_admin']??false)&&!(bool)$accessStmt->fetchColumn()){http_response_code(403);exit('Partner Sales access has not been granted.');}
if($method==='POST'){
 verify_csrf();if(!($me['is_admin']??false)){http_response_code(403);exit('Forbidden');}$action=(string)post('action');$partner=(int)post('partner_user_id');
 if($action==='access'){$target=(int)post('user_id');db()->prepare('UPDATE users SET partner_sales_access=? WHERE id=? AND is_admin=0')->execute([post('enabled')?1:0,$target]);audit('partner_access','user',$target,['enabled'=>(bool)post('enabled')]);flash('success','Partner Sales access updated.');}
 if($action==='review'){$decision=in_array(post('decision'),['continue','watch','pause'],true)?post('decision'):'watch';$rating=max(1,min(5,(int)post('rating')));db()->prepare('INSERT INTO partner_performance_reviews(partner_user_id,reviewer_user_id,decision,rating,notes,review_date) VALUES(?,?,?,?,?,?)')->execute([$partner,$me['id'],$decision,$rating,trim((string)post('notes'))?:null,post('review_date')?:date('Y-m-d')]);audit('performance_review','user',$partner,['decision'=>$decision,'rating'=>$rating]);flash('success','Performance review saved.');}
 redirect('/partner-sales?partner='.$partner);
}
$days=max(7,min(365,(int)($_GET['days']??30)));$users=db()->query("SELECT id,username,is_admin,COALESCE(NULLIF(display_name,''),username) display_name,partner_sales_access FROM users WHERE active=1 ORDER BY display_name")->fetchAll();
$partnerId=($me['is_admin']??false)?((int)($_GET['partner']??0)?:((int)($users[0]['id']??$me['id']))):(int)$me['id'];if(!array_filter($users,fn($u)=>(int)$u['id']===$partnerId))$partnerId=(int)$me['id'];
$summaryStmt=db()->prepare("SELECT COALESCE(SUM(status='won' AND closed_at>=DATE_SUB(NOW(),INTERVAL ? DAY)),0) won_count,COALESCE(SUM(IF(status='won' AND closed_at>=DATE_SUB(NOW(),INTERVAL ? DAY),value,0)),0) won_value,COALESCE(SUM(status='lost' AND closed_at>=DATE_SUB(NOW(),INTERVAL ? DAY)),0) lost_count,COALESCE(SUM(status='open' AND expected_close_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL ? DAY)),0) upcoming,COALESCE(SUM(status='open' AND expected_close_date<CURDATE()),0) overdue FROM opportunities WHERE active=1 AND COALESCE(owner_id,created_by)=?");$summaryStmt->execute([$days,$days,$days,$days,$partnerId]);$summary=$summaryStmt->fetch();
$stageStmt=db()->prepare('SELECT status,COUNT(*) count,COALESCE(SUM(value),0) value FROM opportunities WHERE active=1 AND COALESCE(owner_id,created_by)=? GROUP BY status');$stageStmt->execute([$partnerId]);$stages=array_column($stageStmt->fetchAll(),null,'status');
$dueStmt=db()->prepare("SELECT id,title,value,expected_close_date,probability FROM opportunities WHERE active=1 AND status='open' AND COALESCE(owner_id,created_by)=? AND expected_close_date<=DATE_ADD(CURDATE(),INTERVAL ? DAY) ORDER BY expected_close_date LIMIT 100");$dueStmt->execute([$partnerId,$days]);$due=$dueStmt->fetchAll();
$reviewStmt=db()->prepare("SELECT r.*,COALESCE(NULLIF(u.display_name,''),u.username) reviewer FROM partner_performance_reviews r LEFT JOIN users u ON u.id=r.reviewer_user_id WHERE r.partner_user_id=? ORDER BY r.review_date DESC,r.id DESC");$reviewStmt->execute([$partnerId]);$reviews=$reviewStmt->fetchAll();$partner=array_values(array_filter($users,fn($u)=>(int)$u['id']===$partnerId))[0]??['display_name'=>'Partner'];
layout('Partner Sales',function()use($me,$users,$partnerId,$partner,$days,$summary,$stages,$due,$reviews){?>
<div class="actions"><h1 style="margin:0">Partner Sales</h1><span class="spacer"></span><?php if($me['is_admin']??false):?><form method="get"><select name="partner" onchange="this.form.submit()"><?php foreach($users as $u):?><option value="<?=$u['id']?>" <?=$partnerId==(int)$u['id']?'selected':''?>><?=e($u['display_name'])?></option><?php endforeach?></select><input type="hidden" name="days" value="<?=$days?>"></form><?php endif?></div>
<form class="card actions" method="get"><input type="hidden" name="partner" value="<?=$partnerId?>"><strong><?=e($partner['display_name'])?> performance</strong><span class="spacer"></span><select name="days" onchange="this.form.submit()"><?php foreach([30,60,90,180,365] as $d):?><option value="<?=$d?>" <?=$days===$d?'selected':''?>><?=$d?> days</option><?php endforeach?></select></form>
<div class="grid"><div class="card"><div class="metric"><?=(int)$summary['won_count']?></div>Won<br><strong>$<?=number_format((float)$summary['won_value'],2)?></strong></div><div class="card"><div class="metric"><?=(int)$summary['lost_count']?></div>Lost</div><div class="card"><div class="metric"><?=(int)$summary['upcoming']?></div>Coming due</div><div class="card"><div class="metric"><?=(int)$summary['overdue']?></div>Overdue</div></div>
<div class="card"><h2>Pipeline by stage</h2><table><thead><tr><th>Stage</th><th>Opportunities</th><th>Value</th></tr></thead><tbody><?php foreach(list_options('opportunity_status') as $status):$row=$stages[$status['code']]??['count'=>0,'value'=>0];?><tr><td><?=e($status['label'])?></td><td><?=$row['count']?></td><td>$<?=number_format((float)$row['value'],2)?></td></tr><?php endforeach?></tbody></table></div>
<div class="card"><h2>Due and overdue</h2><table><thead><tr><th>Opportunity</th><th>Expected close</th><th>Probability</th><th>Value</th></tr></thead><tbody><?php foreach($due as $o):?><tr><td><a href="/opportunities/<?=$o['id']?>"><?=e($o['title'])?></a></td><td><?=e($o['expected_close_date'])?></td><td><?=(int)$o['probability']?>%</td><td>$<?=number_format((float)$o['value'],2)?></td></tr><?php endforeach?></tbody></table></div>
<div class="card"><h2>Performance review history</h2><?php foreach($reviews as $r):?><div class="note"><strong><?=e(ucfirst($r['decision']))?> · <?=$r['rating']?>/5</strong><br><?=nl2br(e($r['notes']))?><div class="muted"><?=e($r['review_date'])?> · <?=e($r['reviewer'])?></div></div><?php endforeach?><?php if(!$reviews):?><p class="muted">No reviews yet.</p><?php endif?><?php if($me['is_admin']??false):?><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="review"><input type="hidden" name="partner_user_id" value="<?=$partnerId?>"><div class="form-grid"><label>Review date<input type="date" name="review_date" value="<?=date('Y-m-d')?>" required></label><label>Decision<select name="decision"><option value="continue">Continue partnership</option><option value="watch">Watch performance</option><option value="pause">Pause partnership</option></select></label><label>Rating<select name="rating"><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>"><?=$i?> / 5</option><?php endfor?></select></label><label class="full">Notes<textarea name="notes" required></textarea></label></div><button>Save review</button></form><?php endif?></div>
<?php if($me['is_admin']??false):?><div class="card"><h2>Partner access</h2><p class="muted">Granted users see only their own assigned sales.</p><table><tbody><?php foreach($users as $u):if((bool)$u['is_admin'])continue;?><tr><td><?=e($u['display_name'])?></td><td><?=$u['partner_sales_access']?'Granted':'Not granted'?></td><td><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="access"><input type="hidden" name="user_id" value="<?=$u['id']?>"><input type="hidden" name="partner_user_id" value="<?=$partnerId?>"><?php if(!$u['partner_sales_access']):?><input type="hidden" name="enabled" value="1"><?php endif?><button class="<?=$u['partner_sales_access']?'danger':'secondary'?>"><?=$u['partner_sales_access']?'Revoke':'Grant'?></button></form></td></tr><?php endforeach?></tbody></table></div><?php endif?>
<?php });exit;
