<?php
declare(strict_types=1);
if($path==='/companies'){
 $_GET['view']??='all';
 require_permission('contacts.view');$q=trim((string)($_GET['q']??''));$recordView=(string)($_GET['view']??'mine');$sql="SELECT co.*,COUNT(c.id) contacts FROM companies co LEFT JOIN contacts c ON c.company_id=co.id WHERE co.name LIKE ?";$args=['%'.$q.'%'];if($recordView!=='all'){$sql.=' AND COALESCE(co.owner_id,co.created_by)=?';$args[]=user()['id'];}$sql.=' GROUP BY co.id ORDER BY co.name LIMIT 1000';$s=db()->prepare($sql);$s->execute($args);$rows=$s->fetchAll();
 layout('Companies',function()use($rows,$q){?><div class="actions"><h1 style="margin:0">Companies</h1><span class="spacer"></span><?php if(can('contacts.edit')):?><a class="btn" href="/companies/new">Add company</a><?php endif?></div><form class="card" method="get"><label>Search<input name="q" value="<?=e($q)?>"></label><button>Search</button></form><div class="card"><table><tr><th>Company</th><th>Contacts</th><th>Website</th><th>Updated</th></tr><?php foreach($rows as $r):?><tr><td><a href="/companies/<?=$r['id']?>"><?=e($r['name'])?></a></td><td><?=$r['contacts']?></td><td><?=e($r['website'])?></td><td><?=e($r['updated_at'])?></td></tr><?php endforeach?></table></div><?php });exit;
}
if($path==='/companies/new'){
 require_permission('contacts.edit');if($method==='POST'){verify_csrf();$name=trim(post('name'));if($name!==''){$owner=(user()['is_admin']??false)?((int)post('owner_id')?:user()['id']):user()['id'];db()->prepare('INSERT INTO companies(name,website,phone,address,notes,owner_id,created_by) VALUES(?,?,?,?,?,?,?)')->execute([$name,trim(post('website'))?:null,trim(post('phone'))?:null,trim(post('address'))?:null,trim(post('notes'))?:null,$owner,user()['id']]);$id=(int)db()->lastInsertId();audit('create','company',$id);redirect('/companies/'.$id);}flash('error','Company name is required.');}
 $users=db()->query('SELECT id,username FROM users WHERE active=1 ORDER BY username')->fetchAll();layout('New company',function()use($users){?><h1>New company</h1><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><?php company_form([],true,$users)?><button>Create company</button></form><?php });exit;
}
if(preg_match('#^/companies/(\d+)$#',$path,$m)){
 require_permission('contacts.view');$id=(int)$m[1];$s=db()->prepare('SELECT * FROM companies WHERE id=?');$s->execute([$id]);$co=$s->fetch();if(!$co){http_response_code(404);exit('Company not found');}
 if($method==='POST'){require_permission('contacts.edit');verify_csrf();require_record_edit($co);$owner=(user()['is_admin']??false)?((int)post('owner_id')?:null):($co['owner_id']?:user()['id']);db()->prepare('UPDATE companies SET name=?,website=?,phone=?,address=?,notes=?,owner_id=? WHERE id=?')->execute([trim(post('name')),trim(post('website'))?:null,trim(post('phone'))?:null,trim(post('address'))?:null,trim(post('notes'))?:null,$owner,$id]);audit('update','company',$id);flash('success','Company updated.');redirect('/companies/'.$id);}
 $s=db()->prepare('SELECT * FROM contacts WHERE company_id=? ORDER BY last_name');$s->execute([$id]);$contacts=$s->fetchAll();$users=db()->query('SELECT id,username FROM users WHERE active=1 ORDER BY username')->fetchAll();$editable=can('contacts.edit')&&can_edit_record($co);layout($co['name'],function()use($co,$contacts,$users,$editable){?><h1><?=e($co['name'])?></h1><div class="grid"><form class="card" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><?php company_form($co,$editable,$users);if($editable):?><button>Save company</button><?php else:?><p class="muted">Only the creator, owner, or administrator can edit.</p><?php endif?></form><div class="card"><h2>Contacts</h2><?php foreach($contacts as $c)if(contact_access((int)$c['id'])!=='hidden'):?><p><a href="/contacts/<?=$c['id']?>"><?=e($c['first_name'].' '.$c['last_name'])?></a></p><?php endif?></div></div><?php });exit;
}
function company_form(array $co,bool $editable,array $users): void { $disabled=$editable?'':' disabled';?><div class="form-grid"><label>Name<input name="name" value="<?=e($co['name']??'')?>" required<?=$disabled?>></label><?php if(user()['is_admin']):?><label>Owner<select name="owner_id"<?=$disabled?>><?php foreach($users as $u):?><option value="<?=$u['id']?>" <?=($co['owner_id']??user()['id'])==$u['id']?'selected':''?>><?=e($u['username'])?></option><?php endforeach?></select></label><?php endif?><label>Website<input type="url" name="website" value="<?=e($co['website']??'')?>"<?=$disabled?>></label><label>Phone<input name="phone" value="<?=e($co['phone']??'')?>"<?=$disabled?>></label><label>Address<textarea name="address"<?=$disabled?>><?=e($co['address']??'')?></textarea></label><label>Notes<textarea name="notes"<?=$disabled?>><?=e($co['notes']??'')?></textarea></label></div><?php }
