<?php
declare(strict_types=1);

function normalized_hostname(string $host):string{return strtolower(rtrim(preg_replace('/:\d+$/','',trim($host)),'.'));}
function valid_site_hostname(string $host):bool{return (bool)preg_match('/^(?=.{4,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/',$host)&&!filter_var($host,FILTER_VALIDATE_IP);}

$requestHost=normalized_hostname((string)($_SERVER['HTTP_HOST']??''));
if($requestHost!==''&&!in_array($requestHost,[normalized_hostname((string)parse_url((string)config('url'),PHP_URL_HOST)),'www.'.normalized_hostname((string)parse_url((string)config('url'),PHP_URL_HOST))],true)){
 $q=db()->prepare("SELECT d.*,s.slug site_slug FROM site_domains d JOIN sites s ON s.id=d.site_id WHERE d.hostname=? AND d.status='active' AND s.status='published'");$q->execute([$requestHost]);if($domain=$q->fetch()){$originalPath=$path;$r=db()->prepare('SELECT target_url,http_status FROM site_redirects WHERE site_id=? AND source_path=? AND active=1');$r->execute([$domain['site_id'],$originalPath]);if($redirect=$r->fetch()){header('Location: '.$redirect['target_url'],true,(int)$redirect['http_status']);exit;}$path='/s/'.$domain['site_slug'].($originalPath==='/'?'':$originalPath);}
}

if(preg_match('#^/sites/(\d+)/domains$#',$path,$m)){
 require_permission('sites.edit');$siteId=(int)$m[1];$q=db()->prepare('SELECT * FROM sites WHERE id=?');$q->execute([$siteId]);$site=$q->fetch();if(!$site){http_response_code(404);exit('Site not found');}
 if($method==='POST'){verify_csrf();$action=(string)post('action');if($action==='add'){$host=normalized_hostname((string)post('hostname'));if(!valid_site_hostname($host)){flash('error','Enter a valid domain name.');redirect('/sites/'.$siteId.'/domains');}$token=bin2hex(random_bytes(32));try{db()->prepare('INSERT INTO site_domains(site_id,hostname,verification_token) VALUES(?,?,?)')->execute([$siteId,$host,$token]);audit('create','site_domain',(int)db()->lastInsertId(),['hostname'=>$host]);}catch(PDOException $e){flash('error','That domain is already registered.');}redirect('/sites/'.$siteId.'/domains');}
  $id=(int)post('domain_id');$d=db()->prepare('SELECT * FROM site_domains WHERE id=? AND site_id=?');$d->execute([$id,$siteId]);$domain=$d->fetch();if(!$domain){http_response_code(404);exit('Domain not found');}if($action==='verify'){$records=dns_get_record('_opencrm.'.$domain['hostname'],DNS_TXT);$values=[];foreach($records?:[] as $record)$values[]=(string)($record['txt']??'');if(in_array($domain['verification_token'],$values,true)){db()->prepare("UPDATE site_domains SET status='verified',last_checked_at=NOW() WHERE id=?")->execute([$id]);flash('success','Domain ownership verified. TLS provisioning will run automatically.');audit('verify','site_domain',$id);}else{db()->prepare("UPDATE site_domains SET status='failed',last_checked_at=NOW() WHERE id=?")->execute([$id]);flash('error','Verification TXT record was not found yet. DNS changes can take time.');}}elseif($action==='delete'){db()->prepare('DELETE FROM site_domains WHERE id=? AND site_id=?')->execute([$id,$siteId]);audit('delete','site_domain',$id);}redirect('/sites/'.$siteId.'/domains');}
 $q=db()->prepare('SELECT * FROM site_domains WHERE site_id=? ORDER BY created_at DESC');$q->execute([$siteId]);$domains=$q->fetchAll();$q=db()->prepare('SELECT * FROM site_redirects WHERE site_id=? ORDER BY source_path');$q->execute([$siteId]);$redirects=$q->fetchAll();layout('Domains and redirects',function()use($site,$domains,$redirects){?><div class="actions"><h1 style="margin:0"><?=e($site['name'])?> domains</h1><span class="spacer"></span><a class="btn secondary" href="/sites/<?=$site['id']?>">Back to site</a></div><form class="card form-grid" method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="add"><h2 class="full">Add custom domain</h2><label>Domain name<input name="hostname" placeholder="pages.example.com" required></label><button>Add domain</button><p class="muted full">After adding it, create the shown TXT record and point the domain to this server. OpenCRM verifies ownership before requesting TLS.</p></form><div class="card"><h2>Domains</h2><table><thead><tr><th>Domain</th><th>Required TXT record</th><th>Verification</th><th>TLS</th><th></th></tr></thead><tbody><?php foreach($domains as $d):?><tr><td><?=e($d['hostname'])?></td><td><code>_opencrm.<?=e($d['hostname'])?></code><br><code><?=e($d['verification_token'])?></code></td><td><?=e($d['status'])?></td><td><?=e($d['tls_status'])?></td><td><form method="post"><input type="hidden" name="_csrf" value="<?=csrf()?>"><input type="hidden" name="domain_id" value="<?=$d['id']?>"><button class="compact" name="action" value="verify">Check DNS</button> <button class="compact danger" name="action" value="delete" onclick="return confirm('Remove this domain?')">Remove</button></form></td></tr><?php endforeach?></tbody></table></div><form class="card form-grid" method="post" action="/sites/<?=$site['id']?>/redirects"><input type="hidden" name="_csrf" value="<?=csrf()?>"><h2 class="full">Add path redirect</h2><label>Old path<input name="source_path" placeholder="/old-page" required></label><label>Destination URL or path<input name="target_url" placeholder="/new-page" required></label><label>Status<select name="http_status"><option>301</option><option>302</option></select></label><button>Add redirect</button></form><div class="card"><h2>Redirects</h2><table><tbody><?php foreach($redirects as $r):?><tr><td><?=e($r['source_path'])?></td><td>→ <?=e($r['target_url'])?></td><td><?=$r['http_status']?></td></tr><?php endforeach?></tbody></table></div><?php });exit;
}
if(preg_match('#^/sites/(\d+)/redirects$#',$path,$m)){
 require_permission('sites.edit');if($method!=='POST'){http_response_code(405);exit;}verify_csrf();$siteId=(int)$m[1];$source='/'.ltrim(trim((string)post('source_path')),'/');$target=trim((string)post('target_url'));$status=in_array((string)post('http_status'),['301','302'],true)?(string)post('http_status'):'301';if($source==='/'||($target===''||(!str_starts_with($target,'/')&&!filter_var($target,FILTER_VALIDATE_URL)))){flash('error','Enter a non-root source path and a valid destination.');}else{db()->prepare('INSERT INTO site_redirects(site_id,source_path,target_url,http_status,created_by) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE target_url=VALUES(target_url),http_status=VALUES(http_status),active=1')->execute([$siteId,$source,$target,$status,user()['id']]);audit('create','site_redirect',null,['site_id'=>$siteId,'source'=>$source]);flash('success','Redirect saved.');}redirect('/sites/'.$siteId.'/domains');
}
