<?php
declare(strict_types=1);

function smart_cache_dir():string{$dir=dirname(__DIR__).'/storage/cache';if(!is_dir($dir)&&!@mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Could not create the application cache directory.');return $dir;}
function smart_cache_backend():string{return function_exists('apcu_fetch')&&filter_var((string)ini_get('apc.enabled'),FILTER_VALIDATE_BOOL)?'APCu':'Filesystem';}
function smart_cache_normalize_dependencies(array $dependencies):array{$dependencies[]='cache:global';$dependencies=array_values(array_unique(array_filter(array_map(fn($v)=>mb_substr(trim((string)$v),0,190),$dependencies))));sort($dependencies);return $dependencies;}
function smart_cache_revisions(array $dependencies):array{$dependencies=smart_cache_normalize_dependencies($dependencies);if(!$dependencies)return [];$marks=implode(',',array_fill(0,count($dependencies),'?'));$stmt=db()->prepare("SELECT dependency_key,revision FROM cache_revisions WHERE dependency_key IN ($marks)");$stmt->execute($dependencies);$found=[];foreach($stmt->fetchAll() as $row)$found[$row['dependency_key']]=(int)$row['revision'];foreach($dependencies as $dependency)$found[$dependency]??=0;ksort($found);return $found;}
function smart_cache_storage_key(string $key):string{return 'opencrm:'.hash('sha256',$key);}
function smart_cache_metric(string $name):void{$file=smart_cache_dir().'/metrics.json';$handle=@fopen($file,'c+');if(!$handle)return;try{if(!flock($handle,LOCK_EX))return;$raw=stream_get_contents($handle);$stats=json_decode($raw?:'{}',true)?:[];$stats[$name]=(int)($stats[$name]??0)+1;$stats['updated_at']=date(DATE_ATOM);ftruncate($handle,0);rewind($handle);fwrite($handle,json_encode($stats));fflush($handle);flock($handle,LOCK_UN);}finally{fclose($handle);}}
function smart_cache_fetch_payload(string $storageKey):?array{if(smart_cache_backend()==='APCu'){$success=false;$value=apcu_fetch($storageKey,$success);return $success&&is_array($value)?$value:null;}$file=smart_cache_dir().'/'.substr($storageKey,8).'.cache';if(!is_file($file))return null;$raw=@file_get_contents($file);$value=$raw!==false?@unserialize($raw,['allowed_classes'=>false]):false;return is_array($value)?$value:null;}
function smart_cache_store_payload(string $storageKey,array $payload,int $ttl):void{if(smart_cache_backend()==='APCu'){apcu_store($storageKey,$payload,$ttl);return;}$file=smart_cache_dir().'/'.substr($storageKey,8).'.cache';$tmp=$file.'.'.bin2hex(random_bytes(5)).'.tmp';if(file_put_contents($tmp,serialize($payload),LOCK_EX)!==false){@chmod($tmp,0640);rename($tmp,$file);}else @unlink($tmp);}
function smart_cache_remember(string $key,array $dependencies,callable $loader,int $ttl=300):mixed{$storageKey=smart_cache_storage_key($key);$revisions=smart_cache_revisions($dependencies);$payload=smart_cache_fetch_payload($storageKey);if($payload&&($payload['expires_at']??0)>=time()&&($payload['revisions']??null)===$revisions){smart_cache_metric('hits');return $payload['value']??null;}smart_cache_metric('misses');$value=$loader();smart_cache_store_payload($storageKey,['expires_at'=>time()+max(1,$ttl),'revisions'=>$revisions,'value'=>$value],$ttl);smart_cache_metric('writes');return $value;}
function smart_cache_query(string $namespace,array $dependencies,string $sql,array $params=[],int $ttl=300):array{$key=$namespace.':'.hash('sha256',json_encode([$sql,$params,(int)(user()['id']??0),(int)(user()['role_id']??0)]));return smart_cache_remember($key,$dependencies,function()use($sql,$params){$stmt=db()->prepare($sql);$stmt->execute($params);return $stmt->fetchAll();},$ttl);}
function smart_cache_bump(array $dependencies):void{$dependencies=smart_cache_normalize_dependencies($dependencies);$stmt=db()->prepare('INSERT INTO cache_revisions(dependency_key,revision) VALUES(?,1) ON DUPLICATE KEY UPDATE revision=revision+1');foreach($dependencies as $dependency)if($dependency!=='cache:global')$stmt->execute([$dependency]);}
function smart_cache_invalidate_for(string $action,string $entity,?int $entityId,array $details=[]):void{if(in_array($action,['login','logout','view','download'],true))return;$map=[
 'contact'=>['contacts','reports:contacts','dashboard','opportunities'], 'note'=>['contacts'], 'reminder'=>['contacts','dashboard'],
 'opportunity'=>['opportunities','reports:pipeline','dashboard'], 'opportunity_note'=>['opportunities'],
 'company'=>['companies','contacts','reports:contacts'], 'tag'=>['tags','contacts','opportunities','reports:contacts','reports:pipeline'],
 'tag_group'=>['tags','contacts'], 'custom_field'=>['contacts','reports:contacts'], 'custom_field_group'=>['contacts','reports:contacts'],
 'event'=>['events','reports:events','dashboard','opportunities'], 'event_attendee'=>['events','contacts','reports:events','reports:contacts'],
 'user'=>['users','contacts','opportunities','dashboard'], 'role'=>['permissions','contacts','opportunities','reports:contacts','reports:pipeline'], 'role_permissions'=>['permissions','contacts','opportunities','reports:contacts','reports:pipeline','dashboard'], 'tag_permission'=>['permissions','contacts','opportunities','reports:contacts','reports:pipeline'],
 'custom_field_option'=>['contacts','reports:contacts'], 'custom_field_condition'=>['contacts','reports:contacts'], 'dropdown_option'=>['opportunities','reports:pipeline','events','reports:events'],
 ];$dependencies=$map[$entity]??[];if($entityId)$dependencies[]=$entity.':'.$entityId;if(isset($details['contact_id']))$dependencies[]='contact:'.(int)$details['contact_id'];if(isset($details['opportunity_id']))$dependencies[]='opportunity:'.(int)$details['opportunity_id'];if($dependencies)smart_cache_bump($dependencies);}
function smart_cache_clear():void{db()->prepare('INSERT INTO cache_revisions(dependency_key,revision) VALUES(?,1) ON DUPLICATE KEY UPDATE revision=revision+1')->execute(['cache:global']);$dir=smart_cache_dir();foreach(glob($dir.'/*.cache')?:[] as $file)@unlink($file);if(smart_cache_backend()==='APCu'&&class_exists('APCUIterator'))foreach(new APCUIterator('/^opencrm:/') as $item)apcu_delete((string)$item['key']);@unlink($dir.'/metrics.json');}
function smart_cache_status():array{$metricsFile=smart_cache_dir().'/metrics.json';$metrics=is_file($metricsFile)?(json_decode((string)file_get_contents($metricsFile),true)?:[]):[];$files=glob(smart_cache_dir().'/*.cache')?:[];$bytes=array_sum(array_map(fn($file)=>(int)filesize($file),$files));$revisions=(int)db()->query('SELECT COUNT(*) FROM cache_revisions')->fetchColumn();return ['backend'=>smart_cache_backend(),'entries'=>smart_cache_backend()==='Filesystem'?count($files):null,'bytes'=>$bytes,'revisions'=>$revisions,'hits'=>(int)($metrics['hits']??0),'misses'=>(int)($metrics['misses']??0),'writes'=>(int)($metrics['writes']??0),'updated_at'=>$metrics['updated_at']??null];}
